### PR TITLE
GLM-robust update

### PR DESCRIPTION
**Pull request by kuvychko**
## Summary of changes:
- Updated links to Thomas's blog posts (old links were obsolete/broken)
- Changed code that uses pm.plot_posterior_predictive_glm since this method is no longer in pymc
    - I experimented with arviz.plot_lm but couldn't get a comparable plot
    - Instead, I explicitly computed and plotted a subset of regression lines using coefficients from posterior. Personally I think it is helpful to have an example of a more explicit calculation/visualization like that.
- Updated link to Kruschke's "puppy" book since the link to U of Indiana no longer works. Instead I put a link to Elsevier's book page.
- Updated `rv.logp(x)` method to `pm.logp(rv, x)` since the original method was removed
- Added Authors section at the end of the notebook

### CODE REVIEW

**Comment by kuvychko** [comment]
@OriolAbril @reshamas - it looks like this change hasn't been reviewed yet (I filed this PR 16 days ago). clearly no rush with this, but I want to make sure it doesn't fall through the cracks. Thanks!

**Comment by OriolAbril** [comment]
We currently have 3 PRs open for this same notebook: #356, #445, #451. And I am not sure how to go about this, git conflicts on notebooks are a nightmare. I might try to merge the myst and then update the notebook from it which might happen in a 4th PR overriding the current 3. I will take a look and work on this next week. Thank you all for the PRs, I'll make sure at the very least you are listed as co-author in the merged PR.

**Comment by kuvychko** [comment]
@OriolAbril  - ouch, I see! That's unfortunate, my apologies that it took me so long to finish with it!

**Comment by reshamas** [comment]
@kuvychko 
Can you send me the email address you use for GitHub, so @OriolAbril can add you as a co-author on the GLM-robust notebook?

**Comment by OriolAbril** [comment]
Superseded by https://github.com/pymc-devs/pymc-examples/pull/472

**Comment by kuvychko** [comment]
@reshamas - sure thing, igor.kuvychko@gmail.com

Thanks!!

**Pull request closed without merging**
