### PR TITLE
[DRAFT] Notebook: GLM out-of-sample; initial update

### PR DESCRIPTION
**Pull request by reshamas**
# References
- Towards #394
- Towards #460 
- References [pymc-devs/pymc #5460](https://github.com/pymc-devs/pymc/issues/5460) (Update example gallery style and formatting)
- References Project Board: https://github.com/pymc-devs/pymc-examples/projects/1

+ [x] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [x] PR description contains a link to the relevant issue: a tracker one for existing notebooks or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

### Notes for the Reviewer
- This notebook is being removed because the module GLM is no longer being used in pymc v4.
- See https://github.com/pymc-devs/pymc-examples/issues/460

#DataUmbrellaPyMCSprint

### CODE REVIEW

**Comment by twiecki** [comment]
Missing the myst file.

**Comment by twiecki** [comment]
Actually as this uses the GLM submodule exclusively, which does not exist anymore, we should probably just get rid of this NB.

**Comment by reshamas** [comment]
@twiecki 
The notebook still works with pymc v3.

Should we open up an issue to create a new notebook for pymc v4 with an out-of-sample example?

**Comment by twiecki** [comment]
I don't think we need to invest in v3 docs.

We have https://www.pymc.io/projects/examples/en/latest/howto/data_container.html#using-data-container-variables-to-predict-on-new-data so I think it's fine.

**Comment by reshamas** [comment]
Note to self:  delete the notebook and submit a PR.

**Comment by juanitorduz** [comment]
hey! there was an updated version of this notebook :) See https://github.com/pymc-devs/pymc-examples/issues/460#issuecomment-1341047607

**Comment by drbenvincent** [comment]
I've brought back the v3 -> v4 conversion that I did this summer. It got removed by accident, see #460 for more details. I've run this using pymc 5.0.1 now, so probably recommend we close this in favour of #486.

**Comment by drbenvincent** [comment]
#486 is merged now, so closing this

**Pull request closed without merging**
