### PR TITLE
new Interrupted Time Series notebook

### PR DESCRIPTION
**Pull request by drbenvincent**
New notebook for the causal inference section.

It purposefully follows a very similar template to the causal inference notebooks.

Happy to receive suggestions for improvement of course.

### CODE REVIEW

**Review by lucianopaz — CHANGES_REQUESTED** [review]
Nice work @drbenvincent! I wanted to ask you to rename the mutable data containers. I find the current name very misleading.

After that, it looks good to merge.

**Comment by drbenvincent** [comment]
<p>Good feedback. I've removed the intercept 1's as data and just have <code>beta0</code> now.  And I've renamed the other variable to <code>time</code> which makes much more sense. </p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/444/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>good point. Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/444/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Good point. I've added a brief definition. It is just the difference between the counterfactual prediction and the observed data.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/444/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
> Nice work @drbenvincent! I wanted to ask you to rename the mutable data containers. I find the current name very misleading.
> 
> After that, it looks good to merge.

Thanks! I think I've dealt with all the feedback now. I also additionally improved the generated data, which now uses cleaner 'best practice' pandas.

**Review by lucianopaz — APPROVED** [review]
Looks great @drbenvincent!

**Pull request merged**
