### PR TITLE
Missing data and Bayesian Imputation

### PR DESCRIPTION
**Pull request by NathanielF**
# A notebook on Missing Data methods and Bayesian imputation

Related to https://github.com/pymc-devs/pymc-examples/issues/461

This notebook aims to showcase methods for imputation of missing data using primarily bayesian methods. We will focus on a dataset which records employee satisfaction metrics drawn from the book *Applied Missing Data Analysis*. We will demonstrate how FIML and Bayesian imputation methods work using the Multivariate normal distribution differ and we also want to show how approximate the multivariate distribution using the sequential chained equation methods. 

+ [X] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [X] PR description contains a link to the relevant issue:
  * a tracker one for existing notebooks (tracker issues have the "tracker id" label)
  * or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### CODE REVIEW

**Comment by NathanielF** [comment]
I think this is ready for review now. It's quite long and covers a number of approaches to imputation. 

(I) We discuss the taxonomies of missing-ness (MCAR), (MAR) and (MNAR). I try to set it up as a prelude to considerations about causal inference. 

(ii) FIML and MLE approaches to estimating a multivariate model given missing data
(iii) Bayesian imputation of missing values using the multivariate gaussian and the posterior predictive distribution
(iv) Two examples of imputation using sequential regression equations

Each of the approaches so far is presented in the Enders book and our estimates match those presented there. 

(v) I apply the missing data imputation to hierarchical model and estimate the values of the missing data informed by the structure of "team" clusters in our employee data set. The model is estimated using the blackjax sampler and shows divergences, but converges nicely with good Rhat numbers...,. I use the differences in imputation patterns between the hierarchical model and the simpler regression models to argue for why we need to be aware of heterogenous patterns of imputation and how this is analogous to concerns in causal inference of heterogenous treatment effects. 

We finish on a wrap up and celebration of the flexibility of bayesian modelling in an enterprise that has work with confounding and complexity.

**Comment by fonnesbeck** [comment]
Great tutorial!

**Comment by NathanielF** [comment]
<p>Fair. It was a bit needless. I've taken another approach just adding the patterns of missing-ness as a pandas dataframe: </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1401325036'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Updated and added some more explanatory text</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1401325045'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1401325057'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Removed the idata_uniform entirely as it was a bit overkill. I left the idata_normal. I like having the ability to inspect the model output. Makes reproductions easier to check for consistency. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1401325059'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Thank you for taking the time to review!! Glad you liked it. </p>

**Comment by NathanielF** [comment]
Just giving this a little nudge @drbenvincent. Hope your weekend move went smoothly!?

**Review by drbenvincent — COMMENTED** [review]
Left some comments via nbreview.

Overall really cool. Bit of a vague comment, but I'd be tempted to add in a little more explanation. But that's just my own style, so feel free to ignore. For this more advanced level, it's quite possibly the case that people don't need more hand holding. Nevertheless, if you wanted to add some, it could make it more accessible to a broader range of readers.

House move is ongoing... the actual move won't happen for another month or so :)

**Comment by NathanielF** [comment]
Perfect, thanks @drbenvincent. Will adjust this evening.

**Comment by NathanielF** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859656'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Yes</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859706'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>I thought he just meant the legend in the picture i.e. the color labels for Empowerment etc... which were missing at the time he commented but are there now for me. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859755'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>	Changed this</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859728'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Linked to that notebook too. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859687'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859676'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
That should be good to go now @drbenvincent. I've tidied a few things and added some more explanatory text to sign post what i'm doing a bit more. I think i've also addressed all comments above.

**Comment by drbenvincent** [comment]
<p>Sorry if I'm missing it, but can't see a reference to the example</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859687'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Thanks! A quick find shows up some remaining examples which are not actual L2 markdown headings. ## Percentage Missing in this cell. A bunch in cell 31, one in cell 11.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859728'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Ah yes, Chris meant legend, but I meant figure caption :)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859755'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by drbenvincent — COMMENTED** [review]
Looks good. I added in a few minor replies to comments, but happy to approve after that.

**Comment by NathanielF** [comment]
<p>Just above introducing the employee data set below the MNAR definition</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859687'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>👍🏻</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859687'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Agh... sorry. I think i've got them all now. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/500/discussion/#comment-1411859728'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by drbenvincent — COMMENTED** [review]
Great

**Review by drbenvincent — APPROVED** [review]
Great stuff 👍🏻

**Pull request merged**
