### PR TITLE
binomial regression example

### PR DESCRIPTION
**Pull request by drbenvincent**
Here's a new example for binomial regression. I've specifically not used the glm module in order to make absolutely everything totally transparent. Hopefully there's a decent amount of intro / explanation here to be useful for total beginners.

I believe everything is best practice - although not sure about setting random seed when sampling from a scipy distribution in the data generation part.

Let me know if you can think of any edits.

### CODE REVIEW

**Comment by ricardoV94** [comment]
Very neat and directly to the point!

**Comment by drbenvincent** [comment]
> Very neat and directly to the point!

Thanks @ricardoV94. Think I've sorted everything you've mentioned now :)

**Review by ricardoV94 — APPROVED** [review]
Looks great! Didn't spot anything else.

**Comment by drbenvincent** [comment]
Just spotted and fixed a minor mistake - it wasn't using the seeded rng. So just changed `np.random.binomial` to `rng.binomial`

**Comment by ericmjl** [comment]
@drbenvincent thanks a lot, I like the explanations in here too! I don't see any other issues, so let's hit the merge button.

**Comment by drbenvincent** [comment]
Thanks @aloctavodia - will submit a new pull request soon

**Pull request merged**
