### PR TITLE
fixed bug introduced by rasterio update

### PR DESCRIPTION
**Pull request by Dekermanjian**
# Fixed bug introduced by `rasterio` update
Resolves issue #735 

----
📚 Documentation preview 📚: https://pymc-examples--745.org.readthedocs.build/en/745/

### CODE REVIEW

**Review by OriolAbril — COMMENTED** [review]
Fix looks good. I just realized that the notebook uses the extra dependencies template but doesn't specify which are the dependencies in the metadata. Do you mind fixing this here too?

Here is how the dropdown looks for this notebook:

imatge


And how it looks for one of the HSGP ones that also uses the template:

imatge

**Comment by Dekermanjian** [comment]
@OriolAbril yes, I will definitely fix it! Sorry, I didn't realize it wasn't correct earlier.

**Comment by Dekermanjian** [comment]
Hey @OriolAbril, how do I add the dependencies into the metadata? I tried adding it straight into the associated .myst.md file but that doesn't seem the right way to do it.

**Comment by OriolAbril** [comment]
changes in the myst files get overriden by the contents of the jupyternotebook in pre-commit. You have to either follow the instructions in https://www.pymc.io/projects/docs/en/latest/contributing/jupyter_style.html#extra-dependencies or modify the myst file, then manually call `jupytext` to convert myst->ipynb before pre-commit (not sure if outputs will be removed when doing this so I'd recommend the first option)

**Comment by OriolAbril** [comment]
I don't use vscode but it would be nice to add how to do it from there to the docs

**Review by OriolAbril — APPROVED** [review]

**Pull request merged**
