### PR TITLE
[WIP] Update glm-logistic with bambi

### PR DESCRIPTION
**Pull request by chiral-carbon**
Addresses issue #82 and aims to advance it to best practices, use `bambi` instead of pymc glm module.

I had a question regarding the family to be used in cells 4 and 14 while defining the model. The notebook originally uses Binomial family with the GLM module but with `bambi` I think we do not have a default binomial family defined. I used `negativebinomial` just in case but since it is not the correct replacement, what should I do about it?

### CODE REVIEW

**Comment by tomicapretto** [comment]
Hi @OriolAbril, thanks for tagging me here! 

Actually, I realized it wasn't so much work to implement some stuff to have the Binomial family. It's still being implemented in formulae (see https://github.com/bambinos/formulae/pull/40), and it will be implemented in Bambi after that. 
As for the timeline, this should be done for the next release which will happen when GSoC ends.

**Comment by chiral-carbon** [comment]
thanks a lot @tomicapretto , means a lot to me! :smile:

**Comment by tomicapretto** [comment]
Hi @chiral-carbon. Bambi development version now has a Binomial family :tada: 
Have look [here](https://tcapretto.netlify.app/post/2021-08-03-binomial-family-in-bambi/) to see how it works (and how it compares to the existing Bernoulli family)

**Comment by chiral-carbon** [comment]
this is great @tomicapretto!

**Review by OriolAbril — APPROVED** [review]

**Pull request merged**
