### PR TITLE
Fix Broken Link in Weibull Accelerated Failure Time Model Notebook

### PR DESCRIPTION
**Pull request by pradyutf**
### Summary
This PR addresses the issue [#661]. It updates the link as suggested in the issue description.

### Changes
- Updated the link in the .pynb file
- Updated the link in the .md file

### Additional Notes
Please review and let me know if any further changes are needed or if there are any other links that need updating.

Thank you!

----
📚 Documentation preview 📚: https://pymc-examples--677.org.readthedocs.build/en/677/

### CODE REVIEW

**Comment by cluhmann** [comment]
Thanks so much for opening this PR. Can you check out this section of the [Jupyter style guide](https://www.pymc.io/projects/docs/en/latest/contributing/jupyter_style.html#myst-guidelines), because I think that's how the link needs to be fixed.  If the notebook that needs to be linked to doesn't have the `(notebook_name)=` attribute, then I think that should be added to the target notebook first, and then the link can be updated in the Weibull notebook.

Let me know if that's unclear (it may be).

**Comment by pradyutf** [comment]
Thanks so much for your guidance! I apologise for the oversight. I've now updated the link in the Weibull notebook using {ref} as suggested and added the required (bayes_param_survival_pymc3)= attribute to the target notebook.

I wasn't able to check this change locally. Could you provide some guidance on how to do that or let me know if it's necessary?

Please let me know if this fixes the issue and/or there's anything else I need to address.

**Comment by cluhmann** [comment]
Looks correct to me. @OriolAbril ?

**Comment by OriolAbril** [comment]
It seems pre-commit still needs to be run with the latest changes. After that it should be good to go.

Relevant section in the jupyter style guide: https://www.pymc.io/projects/docs/en/latest/contributing/jupyter_style.html#pre-commit-and-code-formatting. If the command there were to not work you can also try `pre-commit run --all`

**Review by OriolAbril — APPROVED** [review]

**Comment by pradyutf** [comment]
Thank you for merging this PR. I appreciate the guidance and patience. Looking forward to contributing more in the future!

**Comment by cluhmann** [comment]
Thanks for your contribution @pradyutf !! :+1:

**Pull request merged**
