### PR TITLE
Updated tag to Generalised linear model

### PR DESCRIPTION
**Pull request by BerylKanali**
Towards https://github.com/pymc-devs/pymc-examples/issues/430 and https://github.com/pymc-devs/pymc-examples/issues/431

I updated the tag "generalized linear models" and "generalized linear model" as recommended by @reshamas 

cc: @reshamas

### CODE REVIEW

**Comment by reshamas** [comment]
@BerylKanali 
Can you also update the tag in the myst file?
https://github.com/pymc-devs/pymc-examples/blob/main/myst_nbs/generalized_linear_models/GLM-model-selection.myst.md

**Comment by BerylKanali** [comment]
> @BerylKanali Can you also update the tag in the myst file? https://github.com/pymc-devs/pymc-examples/blob/main/myst_nbs/generalized_linear_models/GLM-model-selection.myst.md

Made a commit on that.

**Comment by reshamas** [comment]
@OriolAbril @cluhmann 
Would you know if it's required to run pre-commit?

I was wondering if it was possible to make a minor change to both the notebook and myst file without rerunning it.

**Comment by twiecki** [comment]
myst always causes problem. The easiest is to delete the myst file locally and then run precommit to recreate it, commit the ipynb and myst file, and push.

**Comment by cluhmann** [comment]
> @OriolAbril @cluhmann Would you know if it's required to run pre-commit?
> 
> I was wondering if it was possible to make a minor change to both the notebook and myst file without rerunning it.

I think that is possible.  But jupytext will often make changes to notebook (or rather to the corresponding myst files) that you may not expect (e.g., changes to the metadata that you didn't change by hand).  So going in to just change a typo (or whatever) creates more changes that you "see".

**Review by OriolAbril — APPROVED** [review]

**Pull request merged**
