### PR TITLE
glm bambi usage (WIP)

### PR DESCRIPTION
**Pull request by almostmeenal**
addresses issue #91 

- [x] use bambi instead of glm module
- [x] change imports and other possible bad practices, ensure notebook isnt broken and practices like inference_data=true are followed

Note: I've just started hopefully, i'll finish it in a day or two

cc: @OriolAbril

### CODE REVIEW

**Comment by canyon289** [comment]
Skimmed this over and it looks great to me. Will do a more in depth review as well

**Comment by OriolAbril** [comment]
Added several comments, this is great work

**Comment by almostmeenal** [comment]
> Added several comments, this is great work

thankyou @OriolAbril !!!

**Comment by canyon289** [comment]
I think this is great shape now. Can we mark it ready for merge?

**Comment by almostmeenal** [comment]
> I think this is great shape now. Can we mark it ready for merge?

sure thing!

**Comment by twiecki** [comment]
Thanks @almostmeenal!

**Pull request merged**
