### PR TITLE
CFA and SEM with PyMC

### PR DESCRIPTION
**Pull request by NathanielF**
# CFA and SEM with PyMC

Related to this issue here I'm adding a PR to demonstrate the functionality of CFA and SEM models using PyMC
https://github.com/pymc-devs/pymc-examples/issues/695

+ [X] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [X] PR description contains a link to the relevant issue:
  * a tracker one for existing notebooks (tracker issues have the "tracker id" label)
  * or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

----
📚 Documentation preview 📚: https://pymc-examples--698.org.readthedocs.build/en/698/

### CODE REVIEW

**Comment by NathanielF** [comment]
Think this is ready for review @drbenvincent , @cluhmann , @AlexAndorra . Any feedback/pushback welcome.

**Comment by NathanielF** [comment]
Giving this another nudge! 

Thanks!

**Comment by NathanielF** [comment]
No worries.

**Comment by NathanielF** [comment]
<p>Good idea.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814051'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>changed.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814073'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Added links to wikipedia. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814092'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Fixed. Thanks, good catch!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814114'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>It's not used here in this model,  but useful to have computed for analysing the correlations between the constructs post model fit. I demonstrate this below for the full measurement model....</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814126'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Yes, it seemed to help generally boost the ESS. The model samples pretty fast so it was easy enough to just boost the samples. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814156'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Fixed. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814179'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Fixed. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814200'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814226'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Added the global fit comparison for the SEM and full measurement models. The LOO metrics are quite close, but the full measurement model "wins" on this score. I added a note to say we need to consider the value of the trade-off between expressive power of the SEMs and the questions we can answer in the context of simple global fit comparisons. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814240'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Thanks! </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/698/discussion/#comment-2372814140'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
Thanks @fonnesbeck I think i've addressed most of the points you raised. But let me know if you think I should add anything else. 

Note I also re-parameterised the `tau` terms in the final SEM model which seemed to fix the divergences i was getting.

**Comment by fonnesbeck** [comment]
LGTM!

**Review by fonnesbeck — APPROVED** [review]
LGTM!

**Comment by NathanielF** [comment]
Sweet!

**Comment by NathanielF** [comment]
Think you'll have to merge that for me @fonnesbeck, i don't have that power.

**Comment by NathanielF** [comment]
Woo! Thanks @fonnesbeck

**Pull request merged**
