### PR TITLE
Add Besag-York-Mollie notebook

### PR DESCRIPTION
**Pull request by daniel-saunders-phil**
I've been working on a notebook that demonstrates how to build and interpret the Besag-York-Mollie model. The BYM model is a popular choice for spatial data, especially in epidemiology. PyMC just gained an ICAR distribution, which is a key ingredient in the BYM model. There is a well-developed literature on Bayesian approaches to BYM, written largely by folks in the Stan and r-INLA community:

- Stan case study: https://mc-stan.org/users/documentation/case-studies/icar_stan.html
- Journal article version of above: https://www.sciencedirect.com/science/article/pii/S1877584518301175
- Original paper that developed the parameterization of the BYM model: https://arxiv.org/abs/1601.01180
- r-INLA book chapter on BYM: https://becarioprecario.bitbucket.io/inla-gitbook/ch-spatial.html
- An older R bayes package for doing BYM models: https://cran.r-project.org/web/packages/CARBayes/vignettes/CARBayes.pdf

By contrast, there is very little tutorial material written for Python users who want to do Bayesian spatial modeling. So this notebook would help rectify that and maybe make PyMC appealing to a new segment of the data science community.

To do:

- [x] add correct cross-references
- [x] add bibliography
- [x] double check style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
- [x] update extra installs with notebook metadata
- [x] Spell check
- [x] Fix error with watermark at end of notebook
- [x] Remove placeholder file for importing ICAR once it comes out with a PyMC release.
- [x] Add example that shows how to use predictor variables alongside the BYM model.

----
:books: Documentation preview :books:: https://pymc-examples--566.org.readthedocs.build/en/566/

### CODE REVIEW

**Comment by daniel-saunders-phil** [comment]
<p>Yeah that's a good question. My hunch is that everything proceeds the same. The ICAR distribution would capture all the unexplained spatial covariance. If the covariates explain some of the spatial variance, that's great. But I won't think that we require in a change in how we approach the BYM component of the model. The Stan case study (published paper version) includes four covariates and they just stick them into the linear model like:</p><p> </p><p>y = b0 + b1 * x1 + b2 * x2 + ... + bym_components</p><p> </p><p>I omitted adding predictors in my case study to keep things short but maybe its worth including one predictor variable to give us an opportunity to address it.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/566/discussion/#comment-1686868250'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by daniel-saunders-phil** [comment]
<p>I was going to just wait until the next release. Do you know if it's possible to install versions directly from github without them being released? I searched a bit for instructions but came up empty handed.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/566/discussion/#comment-1686868165'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by fonnesbeck** [comment]
@daniel-saunders-phil to answer your install question, since the PR was merged into main, then installing from pip via:

    pip install git+https://github.com/pymc-devs/pymc.git
    
should do the trick.

**Comment by bwengals** [comment]
<p>assuming you have a conda env that you're working out of where you've already installed pymc, you can <a href="https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch" target="_blank">pip install from a specific git repo branch</a>.  Add <code>--no-deps</code> at the end though, this will make pip only install the pymc code and not try and mess with dependencies. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/566/discussion/#comment-1686868165'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>I think it'd be helpful to include other covariates.  If you don't have other covariates and your goal is just smoothing, there are tons of other ways to do that.  Once you're trying to factor out the effects of other covariates then things like ICAR and GPs become a lot more useful. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/566/discussion/#comment-1686868250'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by daniel-saunders-phil** [comment]
> I think it'd be helpful to include other covariates. If you don't have other covariates and your goal is just smoothing, there are tons of other ways to do that. Once you're trying to factor out the effects of other covariates then things like ICAR and GPs become a lot more useful.
> 

Okie I'll add a covariates. If both you and Chris are interested in seeing that example, I can imagine other folks will too. It will take a couple days I reckon. The raw stan data files are a bit of mess 🫠

**Comment by daniel-saunders-phil** [comment]
@fonnesbeck @bwengals I finished adding the covariate business and made a number of other small tweaks. It's ready for another look.

> Might be better to say "original" instead of naive BYM model. Alternatively you could make a distinction between BYM1 and BYM2

Fixed. I think we'll keep it short by not detailing the BYM1 vs 2 distinction - it's well covered in the linked papers.

**Comment by twiecki** [comment]
Thanks @daniel-saunders-phil!

**Comment by bwengals** [comment]
Really nice explanation of the scaling factor, TY @daniel-saunders-phil!

**Pull request merged**
