### PR TITLE
update hierarchical partial pooling notebook

### PR DESCRIPTION
**Pull request by mjhajharia**
- adds dims and coords to use plot_forest without yticklabels, @OriolAbril since the arviz label thing is WIP from what i inferred this seems to be an ok way?
- changed numpy random generator from legacy to default_rng() (the new standard one)

- also, there wasn't a lot to update in this notebook, it was pretty short, if there's things i'm missing let me know!

### CODE REVIEW

**Comment by OriolAbril** [comment]
does the notebook run without changes with both v3 and v4?

**Comment by mjhajharia** [comment]
yes

**Review by MarcoGorelli — APPROVED** [review]
Looks good to me, just left a comment which is more of an FYI than anything else

**Comment by OriolAbril** [comment]
@mjhajharia can you rerun it with v3 for now still and add the post directive and use bibtex references? link to updated style guide: https://github.com/pymc-devs/pymc3/wiki/PyMC3-Jupyter-Notebook-Style-Guide

**Comment by mjhajharia** [comment]
<p>thanks @michaelosthege it came out nice</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/219/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mjhajharia** [comment]
<p>the actual type is correct, <code>var_names="thetas"</code> works as a temporary patch for this case</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/219/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by mjhajharia** [comment]
btw we could maybe add a test for references.bib syntax errors as well, so it gets fixed in pre-commit or something

**Comment by mjhajharia** [comment]
checked the render, everything worked out, I did the requested changes but because of rebasing git doesn't recognise them, can someone approve and merge?

**Review by michaelosthege — APPROVED** [review]

**Pull request merged**
