### PR TITLE
Re-run notebooks that don't need human attention

### PR DESCRIPTION
**Pull request by michaelosthege**
I'm using the following script, located in `pymc-examples/scripts` and accompanied by `todo.txt`, `error.txt` and `success.txt`.
The `todo.txt` has a line with the absolute path to each notebook for which there is currently no other open pull request.

```python
import pathlib
import rerun
import logging


logging.basicConfig(level=logging.INFO)
_log = logging.getLogger(__file__)


DP_SCRIPTS = pathlib.Path(__file__).absolute().parent
DP_REPO = DP_SCRIPTS.parent
FP_TODO = DP_SCRIPTS / "todo.txt"
FP_SUCCESS = DP_SCRIPTS / "success.txt"
FP_ERROR = DP_SCRIPTS / "error.txt"


def run(fp: pathlib.Path) -> bool:
    success = True
    success = success and rerun.apply_replacements(fp)
    success = success and rerun.run_precommit(fp)
    success = success and rerun.execute_notebook(fp)
    success = success and rerun.run_precommit(fp)
    success = success and rerun.commit(fp, "rerun-quickies")
    success = success and rerun.push("rerun-quickies", "mine")

    if success:
        _log.info("✔ All steps succeeded.")
        return True
    else:
        _log.error("❌ Manual investigation needed.")
        return False


if __name__ == "__main__":
    for fp in FP_TODO.open("r").read().split("\n"):
        already = {
            *FP_SUCCESS.open("r").read().split("\n"),
            *FP_ERROR.open("r").read().split("\n"),
        }
        if fp in already:
            _log.info("Skipping %s because it was already processed.", fp)
            continue

        if run(pathlib.Path(fp)):
            FP_SUCCESS.open("a").write(str(fp) + "\n")
        else:
            FP_ERROR.open("a").write(str(fp) + "\n")

```

### CODE REVIEW

**Comment by michaelosthege** [comment]
<p>I have no idea why it was committed then. It must have had a 0 exit code.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/266/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by michaelosthege** [comment]
<p>True, but out of scope. <a href="https://github.com/pymc-devs/pymc-examples/issues/165" target="_blank">Broken Hyperlinks on Website · Issue #165 · pymc-devs/pymc-examples (github.com)</a></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/266/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by michaelosthege** [comment]
<p><code>ConstantData</code>  was not part of <code>4.0.0b1</code>  yet.</p><p>Expecting that we'll have to do more automated re-runs in the near future, I'd like to prioritize determining which notebooks (don't) need manual inspection..</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/266/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by michaelosthege** [comment]
Ready for review.
All other notebooks resulted in errors of varying severity.

**Comment by OriolAbril** [comment]
Thanks, this is even worse than I expected :sweat_smile: and I thought that getting a 50% auto updated would be a huge success. We landed at 10/95

Related to #56 #217 #214 #80 #113 #90 #120 #121 #268

**Review by OriolAbril — APPROVED** [review]

**Comment by OriolAbril** [comment]
will merge in a few minutes after merging some other PRs and releasing a snapshot

**Comment by michaelosthege** [comment]
Many aso failed because I didn't have Bambi installed.
Also there might be a few more OK ones with the fixed pre-commit now. (I didn't restart from the beginning.)

Let's make a list of what we need to do manually - some of that might be candidates for the migration script, or for reversing unnecessary breaks at the API level.

**Pull request merged**
