### PR TITLE
Added General Updates in data_container.ipynb file

### PR DESCRIPTION
**Pull request by KavyaJaiswal**
## Description

File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/pymc3_howto/data_container.ipynb

Addresses issue #108  aims to advance the notebook to the 'Best Practices' State.

#### The changes are as follows

- Used numpy random generator
- Used try...except when loading data with pm.get_data
- Added all relevant libraries to watermark,

### CODE REVIEW

**Review by OriolAbril — COMMENTED** [review]
I haven't commented on ArviZ things yet, they are in the issue already.

**Comment by KavyaJaiswal** [comment]
I'm currently working on the ArviZ related changes and will update it as soon as I complete them.

**Comment by fonnesbeck** [comment]
@KavyaJaiswal any chance of pushing this to completion?

**Comment by KavyaJaiswal** [comment]
I'm really sorry! I am currently busy with my Outreachy internship and don't think I will be able to work on this till August.

**Comment by OriolAbril** [comment]
@KavyaJaiswal let us know if you need any help to finish this or if you prefer someone else take over :smile:

**Comment by KavyaJaiswal** [comment]
@OriolAbril  If it's urgent, someone can definitely take over. If not, I'm finishing my Outreachy internship on 31st August and I can then finish this.

**Comment by OriolAbril** [comment]
It's not urgent, just wanted to have an idea so we can get it done roughly by the end of September

**Comment by KavyaJaiswal** [comment]
Sure

**Comment by KavyaJaiswal** [comment]
Can I start working on this issue again?

**Comment by OriolAbril** [comment]
Yes! You will need to update the PR with the latest changes in main and take a look at the improved style guide https://github.com/pymc-devs/pymc/wiki/PyMC3-Jupyter-Notebook-Style-Guide. Your PR has been frozen but the repo has had a lot of work done to it in many areas! Let us know if you need any help

**Comment by KavyaJaiswal** [comment]
@OriolAbril I believe you sent the wrong link by mistake.

**Comment by OriolAbril** [comment]
fixed, sorry about the confusion

**Comment by OriolAbril** [comment]
@KavyaJaiswal I took the liberty of taking over and finish it so we can merge it in the following days as we have just released the beta version for the pymc 4.0

**Comment by KavyaJaiswal** [comment]
Thank you so much @OriolAbril for finishing this merge request!

**Pull request merged**
