### PR TITLE
Import do from pymc

### PR DESCRIPTION
**Pull request by HarshvirSandhu**
# Fix import

Solves #633 
import `do` from pymc rather than pymc_experimental

+ [x] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html

----
📚 Documentation preview 📚: https://pymc-examples--635.org.readthedocs.build/en/635/

### CODE REVIEW

**Comment by ricardoV94** [comment]
We ahould also remove any text mentions of PyMC-Experimental (if there are any)

**Comment by HarshvirSandhu** [comment]
@ricardoV94 
daft and pymc_experimental are being imported but not in use.
Removing those

**Review by twiecki — APPROVED** [review]

**Review by twiecki — CHANGES_REQUESTED** [review]
Still some syncing pre-commit issues. Do you know how to resolve them or do you need help?

**Comment by HarshvirSandhu** [comment]
@twiecki 
Running pre-commit locally changes the kernelspec in `interventional_distribution.myst.md`
```
kernelspec:
  display_name: Python 3 (ipykernel)
  language: python
  name: python3
```

**Comment by twiecki** [comment]
@HarshvirSandhu OK try to commit with that change.

**Comment by twiecki** [comment]
Thanks @HarshvirSandhu!

**Pull request merged**
