### PR TITLE
Bayesian ab testing for PyMC v4

### PR DESCRIPTION
**Pull request by percevalve**
# Update to enable running under PyMC v4

Addresses [Issue #172 ](https://github.com/pymc-devs/pymc-examples/issues/172)

+ Some sampling is done using `return_inferencedata=False` as part of the code assumes `pm.backends.base.MultiTrace` formatting.
+ In the initial code there was some mix between using `pm.backends.base.MultiTrace` and `az.InferenceData`

### CODE REVIEW

**Comment by aloctavodia** [comment]
Thanks @percevalve for your help. I leave a few comments.

**Comment by percevalve** [comment]
<p>Does not look like it, will just remove them.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/351/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by percevalve** [comment]
<p>Just going to remove all kwargs in this notebook, my understanding of the NB is that this not critical.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/351/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by twiecki — APPROVED** [review]

**Comment by aloctavodia** [comment]
<p>in ArviZ histograms are assumed by default to represent discrete variables, and the numbers of bins take that into account. So for continuous variables or when the number of discrete variables is very large they may require to change how bins are computed, for example by passing a number of bins </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/351/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
