### PR TITLE
Update pymc3_howto/custom_distribution NB to best practices

### PR DESCRIPTION
**Pull request by chiral-carbon**
Aims to advance https://github.com/pymc-devs/pymc-examples/issues/184 to best practices.

### CODE REVIEW

**Comment by OriolAbril** [comment]
> it renders without the dollar sign though in jupyter when I see it locally. will remove the expression from being inline and push again

jupyter, reviewnb and sphinx (via myst) are 3 different ways of rendering notebooks. For our purposes here, what matters is sphinx rendering to work properly. Reviewnb and jupyter should be the same rendering, but sphinx is by design a completely different paradigm as it doesn't render notebooks independently but as a whole and it renders them into a website using extensions and a theme.

**Comment by OriolAbril** [comment]
the references don't look right, you should double check the bibtex source (you can use google scholar to generate it for you). Right now some have 3 somewhat repeated links but not all of them work

**Comment by chiral-carbon** [comment]
I used the bibtex citations provided by the website of the paper themselves, using the doi links does open the correct website so I'm not sure what to change

**Comment by fonnesbeck** [comment]
@chiral-carbon what is the status of this? Is it close to done, or should I close it?

**Comment by chiral-carbon** [comment]
working on it, will update here in a few days

**Comment by drbenvincent** [comment]
Can you remove all `pymc.*` or `pymc3.*` tags in the first code cell?

**Pull request closed without merging**
