### PR TITLE
update BEST pymc-example to PyMC v4

### PR DESCRIPTION
**Pull request by asuagar**
# update BEST pymc-example to PyMC4 #52

## changes

+ [x] update to PyMC 4
+ [x] rename of greek variables spelling them
+ [x] add header
+ [x] update Autorhsip
+ [x] add License section

## potential improvements

+ [ ] use bib file for bibliography references (it could not be tested because Jupyter does not render MyST cells)
+ [ ] deal with NUTS FutureWarning message (it appears to be related to the beta status)

```
FutureWarning: `Model.initial_point` has been deprecated. Use `Model.recompute_initial_point(seed=None)`.
```

### CODE REVIEW

**Comment by OriolAbril** [comment]
> use bib file for bibliography references (it could not be tested because Jupyter does not render MyST cells)

You have the syntax showing how to use references at https://docs.pymc.io/en/latest/contributing/jupyter_style.html#references. Jupyter can't render myst because cross-references, citations... require building _all_ the files that comprise the documentation at the same time. However, jupyter renders only file per file. You can build the docs with sphinx following the guidance on https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md#contributor-guide or push to the PR and wait for the readthedocs check (currently failing due to the date issue in the post directive) to generate a preview.

**Comment by OriolAbril** [comment]
@asuagar you deleted the whole notebook in the latest commit

**Comment by asuagar** [comment]
<p>Following your recommendations:</p><ul><li>the id was updated using (BEST)=</li><li>"hypothesis testing" was added. However, it is not in the actually used tag list https://github.com/pymc-devs/pymc/wiki/Categories-and-Tags-for-PyMC-Examples</li><li>the date was fixed</li></ul>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/265/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by asuagar** [comment]
<p>I forgot to uncomment the line and run all on a clean kernel. Sorry for the oversight. I have done it now.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/265/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by asuagar** [comment]
<p>Ok. The text has been modified. Now it uses "PyMC" only.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/265/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by asuagar** [comment]
<p>The section "License" has been deleted. Now there is only the cell recommended in the link without any title.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/265/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by asuagar** [comment]
<p>Sorry for the mess. I have never done a GitHub commit using the console. It is being a headache trying to figure the right commands. I will try to make a new PR with the new files. Also, the "references.bib" file has been modified with the new references. </p>

**Comment by asuagar** [comment]
@OriolAbril, you have to apologize my inexperience. I have done a new fork and updated two files (BEST.ipynb and references.bib). I do not know if the best option is (1) "Close with comment" this PR and make a new one or (2) doing other thing. I wait for your instructions.

**Comment by OriolAbril** [comment]
<p>the seaborn style should not be used. the arviz one is actually based on it and will look very similar, but the colour cycler of the arviz one is colorblind friendly whereas the one in seaborn is not. I think it's not critical in this particular notebook but it's much easier to review and enforce if we just apply it everywhere and also gives a feeling of coherence as if the notebooks were chapters of a single book instead of a random collection of pymc resources</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/265/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
I added two extra nits now that it seems like the notebook is part of the PR again, but I can't find the notebook in the website preview: https://pymc--265.org.readthedocs.build/projects/examples/en/265/. Maybe it's best to open a new PR. 

Sorry you had issues with git and branches. Were the instructions on https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md not clear enough? What could be changed to make things more clear?

**Comment by asuagar** [comment]
<p>Fixed. "{cite:t}" as recommended.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/265/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by asuagar** [comment]
<p>The problem is not guide itself. It is exhaustive and precise.  The issue is my low level of knowledge of Git and Github. I have never done something similar before. I will do a new PR. Sorry for the inconveniences. </p>

**Comment by asuagar** [comment]
It is curious. The new commits are added to this PR. Would it be better to close this one and start other one?

**Comment by OriolAbril** [comment]
no need for a new PR. This has everything ready :). Here is the preview to the notebook: https://pymc--265.org.readthedocs.build/projects/examples/en/265/case_studies/BEST.html

You'll see that references are missing, even though they are working in other examples. IIRC, bibtex keys are case sensitive, but it looks like the sphinx extension that simulates bibtex functionality doesn't find the citations when using uppercase letters. Can you try using only lowercase? Other than that everything looks great, thanks!

**Comment by asuagar** [comment]
I have updated the references.bib and the notebook for using lowercase references. I hope that it works. Thanks for your patience!

**Review by OriolAbril — APPROVED** [review]
Everything looks great on the preview, waiting for someone else to double check there is nowhere in the code where we could take advantage of v4 features cc @twiecki @ricardoV94 maybe? Then we can merge

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks!

**Pull request merged**
