### PR TITLE
Update gaussian mixture model with ADVI NB

### PR DESCRIPTION
**Pull request by chiral-carbon**
Addresses issue #134 and aims to advance it to best practices

### CODE REVIEW

**Comment by OriolAbril** [comment]
Mean of first component, mean of 2nd component and observations

**Comment by OriolAbril** [comment]
completely insignificant nit but stresses me a bit, `np.arange(2)` could be `[0, 1]`

**Comment by chiral-carbon** [comment]
will change that then @OriolAbril

**Comment by fonnesbeck** [comment]
Let's update this for v4 and push to completion. @chiral-carbon do you have time for this, or do you want to and it off?

**Comment by chiral-carbon** [comment]
@fonnesbeck sorry about the long hiatus! Will update and push it this week.

**Comment by fonnesbeck** [comment]
@chiral-carbon Is there an update here? Happy to take over if you don't have time.

**Comment by chiral-carbon** [comment]
I'll handle it this week, will update you by the weekend if I can't push.

**Comment by drbenvincent** [comment]
Can you remove all `pymc.*` or `pymc3.*` tags in the first code cell?

**Comment by twiecki** [comment]
Can someone else take over?

**Comment by chiral-carbon** [comment]
Sorry for the lack of updates! Please someone else take over my open
issues. I haven't been able to dedicate time to it as I had promised and I
am not able work with pymc v4 quickly enough.

**Pull request closed without merging**
