### PR TITLE
pre-commit autoupdate (except jupytext)

### PR DESCRIPTION
**Pull request by maresb**
Holding back jupytext because I was getting an error locally. We can do it in a 2nd pr.

----
📚 Documentation preview 📚: https://pymc-examples--641.org.readthedocs.build/en/641/

### CODE REVIEW

**Comment by juanitorduz** [comment]
What about using `nbqa ruff my_notebook.ipynb` for the next one ;) ?

**Comment by juanitorduz** [comment]
Haha yes! It is a think and I just wanted to point it out 😄. No need to adopt it though. It does work really well (I use it to format my notebooks for myself).

**Review by juanitorduz — APPROVED** [review]
LGTM

**Comment by OriolAbril** [comment]
superseeded by https://github.com/pymc-devs/pymc-examples/pull/690

**Comment by maresb** [comment]
Great, thanks @OriolAbril!

**Pull request closed without merging**
