### PR TITLE
Update GLM hierarchical & Robust Outlier Detection to best practices

### PR DESCRIPTION
**Pull request by CloudChaoszero**
This PR is the start of https://github.com/pymc-devs/pymc-examples/issues/14

Addresses #87 and #80 and updates the notebooks to "Best Practices"

## Summary

* Have trace objects saved as InferenceData objects via `return_inferencedata=True`.

I'm open to interpretation on if this is what should be the goal for linked issue  https://github.com/pymc-devs/pymc-examples/issues/14.

### CODE REVIEW

**Comment by CloudChaoszero** [comment]
There are some sns plot-related errors, due to the data type change. 
So, I am open to figuring out how to resolve those 😢

**Comment by OriolAbril** [comment]
As a general starting point, https://docs.pymc.io/notebooks/multilevel_modeling.html should be a good starting point to get plots to work. 

Also, can you add links to all 3 addressed issues? It's more important for me to keep track of the updates and their state to have links to the tracker issues than to #14 (which I may end up closing to reduce confusion)

**Comment by OriolAbril** [comment]
@CloudChaoszero I have updated the description to link to both relevant issues, I noticed that the PR is also modifying the hierarchcal binomial notebook but there are no changes it is only reexecuted. In fact you already updated it back in #45 so it's already in "Best Practices", I think the notebook should be excluded from this PR and work only on the other two.

**Comment by OriolAbril** [comment]
@CloudChaoszero it is hard to give better feedback without running the notebook myself and playing around a bit. Do you mind if I do that and push the changes afterwards? I can also try to live code and post a link here (I can't promise it will be anything worth watching though). Let me know how this sounds and if you like the idea we'll coordinate to avoid git conflicts and so on.

**Comment by CloudChaoszero** [comment]
> @CloudChaoszero it is hard to give better feedback without running the notebook myself and playing around a bit. Do you mind if I do that and push the changes afterwards? I can also try to live code and post a link here (I can't promise it will be anything worth watching though). Let me know how this sounds and if you like the idea we'll coordinate to avoid git conflicts and so on.

@OriolAbril  That works! Thanks a bunch, I really appreciate the help  🙏

**Comment by CloudChaoszero** [comment]
Thank you @OriolAbril this works now. 🙏 ❤️  ( Seriously)
Should we proceed with confirming merge, or should there be an additional review?

**Comment by fonnesbeck** [comment]
Thanks @CloudChaoszero . Apologies for the delay in merging.

**Pull request merged**
