### PR TITLE
Update factor analysis nb to v5

### PR DESCRIPTION
**Pull request by erik-werner**
Fix so that the nb doesn't crash at pm.Minibatch

+ [x] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [x] PR description contains a link to the relevant issue:
  * a tracker one for existing notebooks (tracker issues have the "tracker id" label)
  * or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

----
:books: Documentation preview :books:: https://pymc-examples--586.org.readthedocs.build/en/586/

### CODE REVIEW

**Comment by erik-werner** [comment]
Weird testing error:
```
Error: reserveCache failed: Cache already exists. Scope: refs/pull/586/merge, Key: pre-commit-2-3062ff7e79208312406649393529767a0ddbbadd6828c544993cabef7ae8f110-b70d2bc17f390a7fc1fd9e3e69c215cb25e6331d7218c479f779bcced1326092, Version: 25d34710bdd63bed70a22b8204c3e1d0942dc237e098600e3896b4334c6d784f
```

**Comment by erik-werner** [comment]
Reversed to draft PR as I think the sampling of ``F`` might not match the updated equation above. I'll try to figure this out before marking it as Ready for review.

**Comment by erik-werner** [comment]
This turned into a bit of a rabbit hole which I unfortunately don't have time to dive into right now. I propose to just merge in the update to v5 that fixes the crash, and then I'll write an issue for the rest of the work that I think should be done.

**Comment by erik-werner** [comment]
I've added an issue here: https://github.com/pymc-devs/pymc-examples/issues/587.

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
This is great - thanks @erik-werner!

**Pull request merged**
