### PR TITLE
Update GLM hierarchical binomial model to best practices

### PR DESCRIPTION
**Pull request by CloudChaoszero**
This PR is the start of https://github.com/pymc-devs/pymc-examples/issues/14

Addresses #61 and updates the notebook to "Best Practices"

## Summary

* Have trace objects saved as InferenceData objects via `return_inferencedata=True`.
* If an opportunity for using `coords` exists, then add param `coords`

I'm open to interpretation on if this is what should be the goal for linked issue  https://github.com/pymc-devs/pymc-examples/issues/14.

### CODE REVIEW

**Comment by CloudChaoszero** [comment]
Performing required updates to 1-2 files now. 
* Gauging if these are the ideal changes needed.

**Comment by OriolAbril** [comment]
Also, minor note, I think you'll run into merge issues with #24 here.

**Comment by OriolAbril** [comment]
There are merge conflicts now :sweat_smile:

**Comment by CloudChaoszero** [comment]
@OriolAbril Yikes ha-- updated now!

**Comment by CloudChaoszero** [comment]
## Sigma = 5




## Sigma = 10

**Comment by OriolAbril** [comment]
Thanks for the plots with multiple sigmas, it looks like from 5 to 10 it still changes significantly, can you take a look at sigma=20 and sigma=30? no need to post them, only check the intuition that the posterior progressively stops being so influenced by the prior. We are already retrieving the expected values with 10 so everything looks good. Thanks again for the PR :smile:

**Comment by CloudChaoszero** [comment]
> Thanks for the plots with multiple sigmas, it looks like from 5 to 10 it still changes significantly, can you take a look at sigma=20 and sigma=30? no need to post them, only check the intuition that the posterior progressively stops being so influenced by the prior. We are already retrieving the expected values with 10 so everything looks good. 

@OriolAbril  Yeah, so there isn't a significant change in the posteriors after updating to sigma =20, sigma=30, seen below.

And no problem! 😄  This PR gives me some guidance on fully implementing `return_inferencedata` and `coords` changes for this examples repo.
______

## Sigma = 20

Screen Shot 2021-04-04 at 1 45 14 AM


## Sigma = 30

Screen Shot 2021-04-04 at 1 48 39 AM

**Review by OriolAbril — APPROVED** [review]

**Pull request merged**
