### PR TITLE
TIME SERIES Add air passengers notebook

### PR DESCRIPTION
**Pull request by MarcoGorelli**
## Description

Addresses issue #xxx and aims to advance it to 

---

There's relatively few time series notebooks, so here's one I've put together. It shows how to create a Prophet-like model for the air passengers dataset, with prior and posterior predictive checks

### CODE REVIEW

**Comment by MarcoGorelli** [comment]
Thanks for your review @almostmeenal ! Sure, I'll revise xarray and see where I can use it!

**Comment by MarcoGorelli** [comment]
Thanks @twiecki , have updated

> i think pymc3 has a certain color schemes followed in the documentation or something

@almostmeenal do you know where these conventions are laid out? I didn't see anything about colours in the [jupyter style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Jupyter-Notebook-Style-Guide

**Review by twiecki — APPROVED** [review]

**Comment by almostmeenal** [comment]
> Thanks @twiecki , have updated
> 
> > i think pymc3 has a certain color schemes followed in the documentation or something
> 
> @almostmeenal do you know where these conventions are laid out? I didn't see anything about colours in the [jupyter style guide](https://github.com/pymc-devs/pymc3/wiki/PyMC3-Jupyter-Notebook-Style-Guide

hi @MarcoGorelli i'm so sorry about getting back so late, so idk if there's a formal convention, but i think pymc documentation follows this consistent pattern of using `C0` `C1` colors, i heard about it in this issue, while making some interpolated plot. https://github.com/pymc-devs/pymc3/issues/3859#issuecomment-803974293
although im not sure if it is relevant for notebooks or not. its a very minor styling nitpick so nothing to fret about ofcourse

**Comment by almostmeenal** [comment]
> I think the alternative here would be
> 
> pm.sample_prior_predictive(model=linear_with_seasonality)
> 
> but I think using a context manager (`with linear_with_seasonality`) is more idiomatic to PyMC3 - happy to change if you disagree though, is this what you meant?
> 
> [View entire conversation](https://app.reviewnb.com/pymc-devs/pymc-examples/pull/183/discussion/) on ReviewNB

this works!! again, this is a great and useful notebook!! thankyou for putting in all this work!!!

**Review by almostmeenal — APPROVED** [review]

**Comment by twiecki** [comment]
This is a good one, thanks @MarcoGorelli!

**Pull request merged**
