### PR TITLE
Updated BNN notebook for v4

### PR DESCRIPTION
**Pull request by fonnesbeck**
Second try updating BNN notebook after merge conflicts in original.

### CODE REVIEW

**Comment by twiecki** [comment]
The pre-commit has a weird error, it might be to do with the myst file not being created? Does the pre-commit pass for you locally?

**Comment by twiecki** [comment]
And why isn't reviewNB not showing up?

**Comment by cfonnesbeck** [comment]
Added md file. Should work now.

**Review by twiecki — APPROVED** [review]
Looks great!

**Pull request merged**
