### PR TITLE
Migrate Stochastic Volatility notebook for v4

### PR DESCRIPTION
**Pull request by michaelosthege**
I ran the notebook with PyMC main branch commit [5703a9d24](https://github.com/pymc-devs/pymc/commit/5703a9d24ca01da8b81363874e023e59cd18688d), so it's working with `v4`.

Tracker issue #155 

Crossref https://github.com/pymc-devs/pymc/issues/5820

ping @jiz17043

-----

+ [ ] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [x] PR description contains a link to the relevant issue: a tracker one for existing notebooks or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### CODE REVIEW

**Comment by michaelosthege** [comment]
<p>Since this is the Aesara problem on Windows, I can't get rid of them easily.</p><p> </p><p>But I could manually delete the print output from the notebook file 😅</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/343/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by michaelosthege** [comment]
<p>I guess not? But I'm unfamiliar with this model.</p><p>Let me take a screenshot and ask in Slack.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/343/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>I think it's just a seed question (and you should pass rng to sample_prior_predictive). This model varies widely across different draws</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/343/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by twiecki** [comment]
<p>Yeah, manually deleting is fine.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/343/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by michaelosthege** [comment]
Okay, should be done now:
+ [x] Manually removed the output of the first cell.
+ [x] Passing seeds to the sampling functions (prior predictive now has the extreme values)
+ [x] Also edited the watermark to indicate the PyMC `main` commit this was run with.

**Review by twiecki — APPROVED** [review]

**Pull request merged**
