### PR TITLE
Have pooling model images be local as they keep disappearing.

### PR DESCRIPTION
**Pull request by twiecki**
Fixes https://github.com/pymc-devs/pymc-examples/issues/216.

### CODE REVIEW

**Review by OriolAbril — CHANGES_REQUESTED** [review]
Super in favour of adding the images locally, but they should still use the markdown image syntax (which works for both remote and local images) as the html version is parsed as raw content by sphinx, so the images are not copied correctly when generating the html pages, you can see that the preview still has broken images: https://pymc--282.org.readthedocs.build/projects/examples/en/282/case_studies/multilevel_modeling.html#multilevel-and-hierarchical-models

**Comment by canyon289** [comment]
@twiecki FYI theres some bug on github viewer for NB images. @AlexAndorra was running into the same thing

**Comment by cfonnesbeck** [comment]
Working on this now. Will push a fix today.

**Comment by twiecki** [comment]
@fonnesbeck is this superseded by #285?

**Pull request closed without merging**
