### PR TITLE
GP-Smoothing Notebook to V5

### PR DESCRIPTION
**Pull request by juanitorduz**
Update to V5

----
:books: Documentation preview :books:: https://pymc-examples--603.org.readthedocs.build/en/603/

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Weird NB, doesn't even use the GP submodule. Should we even keep it around?

**Comment by juanitorduz** [comment]
> Weird NB, doesn't even use the GP submodule. Should we even keep it around?

Indeed! It is using `GaussianRandomWalk` to smooth the data. It is interesting but I am not sure if important enough to keep it. I do not have strong opinions. (It was more of a low hanging fruit)

**Comment by twiecki** [comment]
Let's delete it.

**Comment by twiecki** [comment]
Still merging so we have the latest in the history.

**Pull request merged**
