### PR TITLE
Timeseries models derived from generative graph

### PR DESCRIPTION
**Pull request by juanitorduz**
As discussed with @ricardoV94 I will port the gist https://gist.github.com/ricardoV94/a49b2cc1cf0f32a5f6dc31d6856ccb63#file-pymc_timeseries_ma-ipynb into the PyMC Example Gallery. I will add text and explanation to the existing working code :)

----
📚 Documentation preview 📚: https://pymc-examples--642.org.readthedocs.build/en/642/

### CODE REVIEW

**Comment by juanitorduz** [comment]
I think this one is ready for a first review round. 

I have not been able to make the scan reference work with {func}`~pytensor.scan.basic.scan` nor {func}`~pytensor.scan`... any tips? Thanks

**Review by AlexAndorra — CHANGES_REQUESTED** [review]
Love it @juanitorduz ! Added some comments in ReviewNB for the next round

**Comment by ricardoV94** [comment]
<p>Agree with Alex. The main motivation is you can this framework allows you to define many arbitrary time-series, not just things that are pre-packagend in PyMC. For the AR example, one could for instance add different Noise (StudentT) or covariates that change over time...</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205128'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>Re: collect_default_updates, it tells PyMC that the RV in the generative graph should be updated in every iteration of the loop. Agree with adding more context on how Scan is defined and linking to the PyTensor docs for a deeper dive: <a href="https://pytensor.readthedocs.io/en/latest/library/scan.html" target="_blank">https://pytensor.readthedocs.io/en/latest/library/scan.html</a></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205157'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>May be a good excuse to use <code>pm.observe</code> instead of the dummy MutableData </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205192'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>Agree. Let me know if something breaks</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205230'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>Maybe add a second more complex example, either MA2 <a href="https://gist.github.com/ricardoV94/a49b2cc1cf0f32a5f6dc31d6856ccb63#file-pymc_timeseries_ma-ipynb" target="_blank">https://gist.github.com/ricardoV94/a49b2cc1cf0f32a5f6dc31d6856ccb63#file-pymc_timeseries_ma-ipynb</a> or one of those Jesse wrote here <a href="https://gist.github.com/jessegrabowski/ccda08b8a758f882f5794b8b89ace07a" target="_blank">https://gist.github.com/jessegrabowski/ccda08b8a758f882f5794b8b89ace07a</a> ?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205128'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jessegrabowski** [comment]
<p>I think a discussion of conditional and unconditional posteriors is needed here. Many users will be surprised by this posterior because they are used to seeing conditional one-step forecasts, $p(x_t | \{x_\tau\}_{\tau=0}^{t-1})$ (what you get in statsmodels/stata/everything), which are much tighter and follow the data more closely. </p><p> </p><p>At the risk of scope-creep, I think it's also important to show users how to use a predictive model to get the conditional posterior. It would also be the first place in pymc-examples that shows how to use a predictive model -- up until now we only have the labs blog.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205261'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jessegrabowski** [comment]
<p>Why is there an observed value for the initial condition? We never observe this by definition.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205192'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>Showing a non-recursive time varying parameter could be useful though? Can split into two separate notebooks?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205128'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jessegrabowski** [comment]
<p>I think that's a good 2nd example, because it also serves as a tutorial on the difference between <code>outputs_info</code>,<code>sequences</code>,and <code>non_sequences</code>      </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205128'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>I don't see why you can't observe it? </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205192'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jessegrabowski** [comment]
<p>Because the first observation in the data is $x_0$, so the initial conditions $x_{-1}$ and $x_{-2}$ are by definition unobserved</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205192'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jessegrabowski** [comment]
<p>I blatently plagerized this notebook and used <code>pm.observe</code> in a <a href="https://discourse.pymc.io/t/multivariate-ar-1-stochastic-volatility-model/13992/3?u=jessegrabowski" target="_blank">discourse thread here</a>, maybe it could be helpful. </p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205230'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
Ok! Now that the HSGP example was merged I can come back to this one. Apologies for the delay 🙈😄.

**Comment by ricardoV94** [comment]
> Thank you all for the feedback! Now that the HSGP example was merged I can come back to this one (there are no dependencies but I was busy with other stuff 🫠). Apologies for the delay 🙈😄.

Awesome!

**Comment by juanitorduz** [comment]
<blockquote>Maybe add a second more complex example, either MA2?</blockquote><p> </p><p>I suggest we keep this notebook simple and work out other more complex examples in a different notebook (I can also work on it). In my experience, the first time an user sees these models can be overwhelming, so let's keep it simple for this one :D</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205128'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Addd more info!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205157'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>@jeseegrabowski I used the code you shareed on discourse and that is why I added you as a co-author :)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205192'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Fixed in <a href="https://github.com/pymc-devs/pymc-examples/pull/642/commits/67ec83d469008d39a65ce744e65e1bffbe5c0fbe" target="_blank">67ec83d</a></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-1989205230'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
@jessegrabowski I think your point about conditional vs unconditional posterior is indeed very important!  In order to generate the conditional posterior, do I need to condition on the whole observed time series? Do you have a snippet od code to do this ?

**Comment by jessegrabowski** [comment]
You'd take the posterior parameters and scan over the observations, setting each observation as $y_t$ then predicting $y_{t+1} | y_t, \theta$. Here's a quick gist I whipped up that I think does the right things:

https://gist.github.com/jessegrabowski/d3ea37e521dc3e63d89864d0bbcf54e0

**Comment by juanitorduz** [comment]
> You'd take the posterior parameters and scan over the observations, setting each observation as yt then predicting yt+1|yt,θ. Here's a quick gist I whipped up that I think does the right things:
> 
> https://gist.github.com/jessegrabowski/d3ea37e521dc3e63d89864d0bbcf54e0

Wow! Cool! I will take a look at it in detail!

**Comment by jessegrabowski** [comment]
I made errors in that gist and you inherited them, sorry. In particular, you have to shift the dates in the coords forward by 1, because the data at (for example) 2001-01-01 is used to create the prediction for 2001-02-01. If you just re-use the old dates, the 2001-02-01 prediction will be mislabeled as 2001-01-01, and your model will look better than it is. In general, there should be some "chasing" visible, where the conditional posterior looks like a forward shifted version of the data (because that's what it is!)

I updated the gist to fix this error, and also added a section on forecasting that might be interesting as well.

**Comment by juanitorduz** [comment]
@jessegrabowski That gist is gold! I would love to have them in the examples as well as it shows how to handle with hidden states (non that relevant for AR model). 

I tried to implement this in the AR(2) model and compare it with statsforecast. WDYT?

**Comment by juanitorduz** [comment]
@jessegrabowski @ricardoV94 just a small reminder this one is ready for review 😄.

**Comment by ricardoV94** [comment]
> @jessegrabowski @ricardoV94 just a small reminder this one is ready for review 😄.

It's on my top list, either this weekend or monday!

**Comment by jessegrabowski** [comment]
@juanitorduz sorry I slept on this for so long. I made some suggestions, mostly nitpicks. Overall looks great!

**Comment by juanitorduz** [comment]
<p>Thanks! Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2169185736'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>I added some explanation.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2169185757'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Done!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2169185771'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Done! Thanbks for the reference!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2169185784'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Added!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2169185831'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>yes!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2169185808'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>yes!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2169185866'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>I think as the conditional step has <code>n_steps=trials - lags</code> and the forecasting model has a generic <code>n_steps=forecast_steps</code> it is not that straightforward right? </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2171456856'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Any suggested values ? Changing the seed does not change that much and the rho values go very close to zero many times :D</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2171456827'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
@OriolAbril, I am able to add links to the classes, but the functions and methods won't work for some reason ... do you have any tip :)

**Comment by ricardoV94** [comment]
<p>I don't know if this can be recovered, but perhaps worth a shot? <a href="https://colab.research.google.com/drive/1yLrxTBRPa08B8EIEh6NGWG_aLFxIbanh?usp=sharing" target="_blank">https://colab.research.google.com/drive/1yLrxTBRPa08B8EIEh6NGWG_aLFxIbanh?usp=sharing</a></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2171456827'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>Does that matter? <code>n_steps</code> can also be a Data variable that you change? </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2171456856'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jessegrabowski** [comment]
<p>You could pick parameters that are 1) strongly persistent, and 2) give imaginary eigenvalues and generate oscillating trajectories. For example, rho_1 = 0.99, rho_2 = -0.99/4</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/642/discussion/#comment-2171456827'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
@juanitorduz These seem particular problems.

---

pytensor.scan is **explicitly** not indexed within the pytensor docs as a function: https://github.com/pymc-devs/pytensor/blob/main/doc/library/scan.rst?plain=1#L679. My guess from a quick look at the blame is theano probably had `any` type references which attempt to automatically resolve to any of the possible types, but `pytensor.scan` is both a module and a function in theano/aesara/pytensor and it seems in aesara times `:noindex:` was added in multiple places to get those to "work" again.

It looks like the main alternative right now is using `` {mod}`pytensor.scan` `` (which is the indexed entry for `pytensor.scan`). Another option could be keeping `func` and fixing it on pytensor end, or using the [ref type cross-reference to the top of the page](https://github.com/pymc-devs/pytensor/blob/main/doc/library/scan.rst?plain=1#L2), that is `` {ref}`scan <lib_scan>`

---

For `pymc.model.transform.conditioning.observe` there doesn't seem to be anything remotely close to that in the pymc docs: https://www.pymc.io/projects/docs/en/latest/api/model.html. If I do look at the source though, I do see a `model/conditioning` entry which doesn't exist within that folder: https://github.com/pymc-devs/pymc/tree/main/docs/source/api/model, and the `transform` file is missing, so my guess is it was renamed but the toctree entry not updated, so it is not part of the website navigation tree anymore.

Here you should leave the reference correctly added and then it needs to be fixed on pymc end (once that is done, regenerating the examples will fix the issue without any extra work). Regarding fixing on the pymc docs, do we really expect users to use `pymc.model.transform.conditioning.observe` when they import `observe`?

If not, use the actual import path in the reference, and when fixing it document it where the users are expected to import it from (in this case `pymc.observe` as it is done in the notebook itself), the file structure of the library is completely irrelevant to users and should have no place in the public API docs.

If yes, then the notebook would need to be updated to use that.

**Comment by juanitorduz** [comment]
Thank you very much @OriolAbril ! (and apologies for the late reply, these last two weeks have been hectic 🫠)

**Comment by ricardoV94** [comment]
@juanitorduz let us know if you need anything else from us at the moment

**Comment by juanitorduz** [comment]
Apologies @ricardoV94 🙈. I just need some time... Thinks are busy at this stage 🫠. Thanks for checking in! This PR is still in my todo list.

I think the main content is there: I just need to address the two open points:

- write a function to reuse code 
- change the input series to make it less volatile

**Comment by juanitorduz** [comment]
Next week I'll have the time to work on this one 🙏

**Comment by juanitorduz** [comment]
@ricardoV94 @jessegrabowski Sorry for the late reply, but I am particularly busy (not just work, but kids and moving and...). Anyway, I cleaned up and updated the PyMC version (5.16). Regarding the open points:

- @jessegrabowski  `trials` - > `timeseries_length` I this the change ✅ . I agree that having it as a global variable is not ideal, but it serves the example's illustrative purposes. This was a gist I received from @ricardoV94, and changing it to have it as a function will take more time, and I think we should work on iterations.

- @ricardoV94 Combining the conditional and forecasting distributions via the do operator is not as straightforward because the scan outputs are different (one uses `sequences` and the other `utputs_info`). Even though I am sure one can combine them, for me, learning this material, having them separate and more "verbose" makes it easier to follow (still, this is a personal opinion)

@ricardoV94 Making the series smoother: I could use @jessegrabowski 's suggestion of setting the values for rho directly. But then I would need to generate the series again instead of using the prior samples, which I believe was the idea of the initial gist. This, again, would require more work for the first iteration. 

All in all, I think this notebook is in a very good state for the first iteration. I suggest we merge this one, and then we can take over additional enhancements in future PRs. This is very cool material and needs to be exposed to the users ;) 

WDYT? 

(Again, apologies for the time constraints to address all the comments in this iteration 🙏 )

**Comment by ricardoV94** [comment]
@juanitorduz sounds good with me

**Comment by twiecki** [comment]
Let's make sure we advertise this one. Do you want to post it @juanitorduz?

**Comment by juanitorduz** [comment]
I will do so!

**Pull request merged**
