### PR TITLE
Spline example

### PR DESCRIPTION
**Pull request by jhrcook**
## Description

Addresses issue #230 and aims to advance it to Best Practices.

This PR is for a contribution of an example of a spline regression in PyMC3.

### CODE REVIEW

**Comment by canyon289** [comment]
Hey Josh,
Apologies on the delay. This is a fantastic contribution so well merge. Know we might replace the figures with matplotlib figures sometime down the road but that has nothing to do with the quality of your work, moreso with the headache of maintaining notebooks over a number of years, especially ones we want to keep around like this one!

**Review by canyon289 — APPROVED** [review]

**Comment by jhrcook** [comment]
You reviewed and merged this within a day, so no need to apologize for a delay. Again, I’m happy I could contribute to PyMC3 given how much it and the community have helped me. If possible, could you add the label `hacktoberfest-accepted` to this PR so I can get credit for [Hacktoberfest](https://hacktoberfest.digitalocean.com)?

**Comment by canyon289** [comment]
Of course

**Comment by OriolAbril** [comment]
I added the hacktoberfest topic to the repo which I think was the reason it did not count. From what I understand reading https://hacktoberfest.digitalocean.com/resources/maintainers, PRs only need the hacktoberfest-accepted label if they are not approved nor merged during October. 

Let us know if things are working now

**Pull request merged**
