### PR TITLE
Update Mediation analysis notebook to best practice

### PR DESCRIPTION
**Pull request by drbenvincent**
#171 

This should update this notebook to best practice. Just let me know if there's anything I missed.

### CODE REVIEW

**Comment by drbenvincent** [comment]
References not rendering?

**Comment by OriolAbril** [comment]
> References not rendering?

looks like the backticks are missing. https://docs.pymc.io/en/latest/contributing/jupyter_style.html#references

**Comment by drbenvincent** [comment]
That should be most of the obvious errors fixed.

**Comment by drbenvincent** [comment]
<p>I'm not sure I understand. You mean set the date to when the notebook was originally published (ie August 2021) ?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/280/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Values are:</p><ul><li>cprime: 0.002665</li><li>indirect effect: 0.002359</li><li>total effect: 0.001165</li></ul>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/280/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/280/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
> I'm not sure I understand. You mean set the date to when the notebook was originally published (ie August 2021) ?

No, leave the post directive as it is currently. This is a comment on the text below about using best practices that uses the word "now" which readers won't know how to interpret, they won't see the date in the post directive when reading the notebook

**Review by OriolAbril — APPROVED** [review]

**Comment by OriolAbril** [comment]
<p>now seeing the graphviz on the website, if you can annotate the likelihoods it will probably be more clear for readers, grouping all the vector variables under the same plate</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/280/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
You mean having a single vector of beta coefficients rather than `beta0` and `beta1` as separate variables? I think that's just a matter of taste. For example, if you have unnormalised data, it's easier to specify different priors. But if that's a strong view then I'm happy to do that. Let me know...

**Comment by OriolAbril** [comment]
In the `m_likelihood` and `y_likelihood`, now they look like a different dimension from the graphviz:

imatge

it's a super minor nit. Model parameters are perfectly fine as they are.

**Comment by drbenvincent** [comment]
My fault... I was looking at the wrong notebook in the docs! Will experiment adding in `dims` for the likelihoods...

**Comment by drbenvincent** [comment]
If the DAG does not look changed, it's a cache issue. Looking in a different browser shows it correctly, like this
Screenshot 2022-02-14 at 14 46 58

**Comment by OriolAbril** [comment]
<p>We ended up deciding to suggest some names (which are listed in the dropdown at https://docs.pymc.io/en/latest/contributing/jupyter_style.html#variable-names) but not to enforce them. I don't think <code>result</code>  makes the notebook harder to understand and I think it's not an issue to keep it.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/280/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
<p>I prefer not using Deterministic unless we <em>need</em> those values to be in the resulting inferencedata. I have found some people who think deterministic is needed for all itermediate results and end up very quickly with posterior samples that don't fit in memory due to that. I do agree with annotating dims in yy</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/280/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Luciano has confirmed this is still the way to provide a seed to <code>pm.sample</code></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/280/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done... have added in <code>dims="obs_id"</code></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/280/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
If I understand right from @OriolAbril's comments, I think this is ready to merge?

**Comment by OriolAbril** [comment]
> If I understand right from @OriolAbril's comments, I think this is ready to merge?

I can use my admin privileges to merge, and will do so in a few days as I won't go behind anyone to get reviews here (or anywhere). 

But I can't help but fear we are going towards some kind of no man's land that I think is bad and even dangerous for the project. The library keeps advancing but the docs lag more and more behind to the point that not even core developers are aware of the changes and improvements being done (in addition to them not being documented anywhere).

I see that in random seeds and in use of `dims` but I am not aware of all the changes happening (nor I intend to be, I am aware of all doc related changes which is more than enough for me).

Re random seeds to use as an example, I don't really care much about the random seed personally and I couldn't care less about the specific persons involved in the comments here, this is something I see as a general issue that concerns the whole team. I saw a PR/notebook (not sure which) seeding from the model context and asked on slack:

> what is the right way to seed sampling in v4? (or if not yet implemented, what will be the way?) Some of the notebooks being updated to v4 use the pm.sample call like in v4 but others use the pm.Model context. It seems like a bad idea to use both things indistinctively in the documentation, especially in beginner notebooks

and got this answer:

> I think we still need to figure it out. There's a lot of things that need seeding in different places... I guess the first step is to check if everything we want to be seeded is called from a Model context or not.

which differs from https://github.com/pymc-devs/pymc-examples/pull/280#issuecomment-1035352631. 

How, when, and where do we expect users to learn v4 and take advantage of all the improvements?

**Comment by ricardoV94** [comment]
<p>Both methods work, we need to discuss which one we want to be the standard</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/280/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
