### PR TITLE
improvements to glm.ipynb

### PR DESCRIPTION
**Pull request by mjhajharia**
glm.ipynb is not broken anymore after #177, a few minor updates in documentation or markdown cells are still left, doing them in this PR as i get time, nothing urgent, but everyone feel free to make suggestions!!!!

### CODE REVIEW

**Comment by almostmeenal** [comment]
@OriolAbril I've taken care of all the comments, copying this comment from the previous PR over here so it stays in my head.

_

> The explanation is great and the link to the family object too. I also have a myst related extra note here (again, so not implement yet) that we could use intersphinx for that link so that if bambi decides to rename master to main, we'll only have to change a link in conf.py and regenerate docs for everything to work again, otherwise we'll have to track down all links and update them. Same thing if documentation is reorganized, files renamed or moved to a different folder structure

_

**Review by MarcoGorelli — APPROVED** [review]
looks good to me

**Comment by fonnesbeck** [comment]
@almostmeenal just address Oriol's comment and this is good to merge.

**Comment by almostmeenal** [comment]
thanks a ton for the help @OriolAbril !!!!

**Comment by almostmeenal** [comment]
@fonnesbeck this is done, i'm sorry for the delay :((

**Pull request merged**
