### PR TITLE
Rerun vi

### PR DESCRIPTION
**Pull request by ferrine**
related to #333

### CODE REVIEW

**Comment by ferrine** [comment]
Read the Docs error is weird. So far I have some issues rerunning variational quick start due to mixtures refactoring

**Comment by drbenvincent** [comment]
Hi @ferrine. Please remove all `pymc.*` and `pymc3.*` tags in the first code cells of all notebooks.

**Comment by drbenvincent** [comment]
Just to be clear, it's not just the `pymc` that needs to be removed, but the entire tag. Eg. `pymc.Minibatch` needs to disappear completely, not just the `pymc.`

**Comment by ferrine** [comment]
@drbenvincent got it, will fix

**Comment by OriolAbril** [comment]
I tried running the notebooks locally to see if it fixed the encoding issues in the docs build but some notebooks don't seem to run anymore with the latest release. Can someone else try to run them?

**Comment by fonnesbeck** [comment]
@ferrine do you want me to fix and finish this PR?

**Comment by OriolAbril** [comment]
superseeded by #497

**Pull request closed without merging**
