### PR TITLE
update GLM out of sample prediction notebook to v4

### PR DESCRIPTION
**Pull request by drbenvincent**
ref #85 

- Updated to v4
- Added various markup elements
- Removed mention of PyMC3 and also of dead notebooks
- Minor refactoring of some code just to keep the global scope clean and to increase readability a little
- switched to `rng = np.random.default_rng` as per the style guide. Along the way the random seed for sampling got removed. Can always put that back if need be.

### CODE REVIEW

**Comment by drbenvincent** [comment]
<p>Done, in upcoming commit</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/370/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>removing this in upcoming commit</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/370/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Agreed</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/370/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Doesn't need to be because I used labels for the coefficient names. But here I agree, so I've changed them to b0, b1, b2, b1:b2</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/370/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>I've removed the last sentence</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/370/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cluhmann** [comment]
<p>I guess I meant that <code>x1</code> here (i.e., <code>idata.posterior.b.sel(coeffs="b1").mean().data</code>) is the mean posterior of a coefficient that is labeled "b1", which is then multiplied by the "x1" taken from the grid   (i.e., x1_grid).  So I guess I assumed that <code>idata.posterior.b.sel(coeffs="b1").mean().data</code> would be stored in a variable named <code>b1</code> rather than <code>x1</code>.</p><p> </p><p>Also, as in the comment resolved above, I tend to do:  <code>idata.posterior["b"]</code> rather than <code>idata.posterior.b</code>.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/370/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Have moved to just using defaults throughout. It doesn't look as good, but do feel free to hold me accountable to improve it and stop me from being lazy</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/370/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by cluhmann — APPROVED** [review]

**Comment by juanitorduz** [comment]
LGTM 🚀

**Comment by drbenvincent** [comment]
@OriolAbril I seem to have an approval from @cluhmann, but it says merging is blocked and that I don't have an approval.

**Review by twiecki — APPROVED** [review]

**Pull request merged**
