### PR TITLE
Replacing PyMC3 plots w/ Arviz plots & sigma Param change

### PR DESCRIPTION
**Pull request by CloudChaoszero**
# Description

Replace PyMC3 dependent plots with arviz plots in case studies & examples.
* The issue is a 3-part step for the following:
  * Initiative via Issue https://github.com/pymc-devs/pymc3/issues/4371 (Leave open)

Replace parameter `sd` with `sigma` (e.g. some examples have `pm.Normal(...sd=...)`
* Closes issue #2

### CODE REVIEW

**Comment by twiecki** [comment]
Woah, @CloudChaoszero is this done / ready for review? Did you do it manually? Did you re-execute the NBs?

**Comment by CloudChaoszero** [comment]
> @CloudChaoszero is this done / ready for review? Did you do it manually? Did you re-execute the NBs?

Yeah, @twiecki I would say this is done! haha (I was watching some tv shows while working on this, over time). This was done manually, and I re-executed most books***.

I do have some notes:

## Notes
1. I'm confident I replaced all Pymc3 plots & diagnostics, regarding pymc-devs/pymc3#4371 (except for `plot_posterior_predictive_glm`, that stays)
2. ***There were some files with hiccups/errors, so I did not re-run them. (Issue found here https://github.com/pymc-devs/pymc3/issues/3959) However, I did replace functions like `pm.traceplot` w/ `az.plot_trace`, etc
3. Added a couple `warnings.ignore()` because the notebooks that ran had my local path on Warnings (e.g. `User/Username/`)

**Comment by twiecki** [comment]
Amazing and much appreciated!

**Comment by AlexAndorra** [comment]
Thanks a lot for this @CloudChaoszero 🤩 
I have one request though: the PR is currently _huge_, so could you chunk it off in several different PRs, each having, let's say 10 notebooks, and then a last one with the `.py` files?
That way, it'll be much easier and faster to review for us, and it'll be easier for you to update the files according to our comments. How does that sound?

**Comment by CloudChaoszero** [comment]
> I have one request though: the PR is currently _huge_, so could you chunk it off in several different PRs, each having, let's say 10 notebooks, and then a last one with the `.py` files?
> That way, it'll be much easier and faster to review for us, and it'll be easier for you to update the files according to our comments. How does that sound?

@AlexAndorra  That works! haha 
* I know what you mean. 
The PR's will be available, shortly.

**Comment by MarcoGorelli** [comment]
Thanks @CloudChaoszero - OK, shall we close this PR then in favour of the others? (I'll take a look at the during the coming week)

**Comment by AlexAndorra** [comment]
Yeah let's do that. Thanks @CloudChaoszero

**Pull request closed without merging**
