### PR TITLE
Ordinal regression

### PR DESCRIPTION
**Pull request by NathanielF**
# Example Notebook using Ordinal Regression Model

Related to this issue: https://github.com/pymc-devs/pymc-examples/issues/277

Notebook is a work in progress. Just experimenting with different model specifications on fake data with known properties. 
Current plan is fit and explain the regression model with a discussion of the priors over the cut points and evaluating different implications of the model specification. Rough plan is to then apply the techniques to examples in Agresti's book on categorical data analysis. 

+ [X] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [X] PR description contains a link to the relevant issue:
  * a tracker one for existing notebooks (tracker issues have the "tracker id" label)
  * or a proposal one for new notebooks
+ [X] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by NathanielF** [comment]
Marking this one as ready for a pull request because I think i have the bones of what I want... but not quite the structure. I also know @drbenvincent has thoughts on this one too. So opening it up for feeback or pushback, suggestions

Broad structure at the moment is 

1. Open with scenario of employee rating system to motivate the view of a latent sentiment and explicit rating. 
2. Generate fake data and visualise it. Explain the nature of the regression model
3. Run a variety of models
4. Plot outcomes 
5. Use Krushcke's movie data set to compound the importance of modelling ordinal data properly 
6. Conclude

**Comment by drbenvincent** [comment]
Great stuff. Reviewing this and the other notebook is definitely on my list 🙂

**Comment by NathanielF** [comment]
Giving this one a nudge @drbenvincent

**Comment by drbenvincent** [comment]
Thanks for the reminder. A bunch of house move things get finished today, so should have capacity for this very soon :)

**Review by twiecki — APPROVED** [review]

**Comment by NathanielF** [comment]
Just giving another nudge here @drbenvincent. At this point i'm pretty happy with it.

**Comment by drbenvincent** [comment]
Sorry, taking a look now :)

**Comment by NathanielF** [comment]
Made those changes. Think we're all good now. Thanks for the review!

**Pull request merged**
