### PR TITLE
Turn off autofix PRs

### PR DESCRIPTION
**Pull request by maresb**
----
📚 Documentation preview 📚: https://pymc-examples--636.org.readthedocs.build/en/636/

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
Is the CI error unrelated?

**Comment by maresb** [comment]
Unrelated. I took a look at the failure and noticed that we were missing autofix. Let's merge and then follow up with the failure.

**Comment by maresb** [comment]
Hmm, #637 is still using the old image. Maybe it's still being tested.

**Comment by maresb** [comment]
Moved discussion of CI failures to a fresh issue: #638

**Pull request merged**
