### PR TITLE
update truncated/censored notebook to v4

### PR DESCRIPTION
**Pull request by drbenvincent**
Following #261, this pull request updates GLM-truncated-censored-regression.ipynb

Changes:
- uses pm.Censored
- I've _hopefully_ updated it to conform to the new style guide

### CODE REVIEW

**Comment by drbenvincent** [comment]
<p>Good point. Amending this text</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>This reviewnb doesn't show all cells. But it is actually there and defined...</p><pre class="ql-syntax" spellcheck="false">def truncated_regression(x, y, bounds):
&nbsp;&nbsp;with pm.Model() as model:
&nbsp;&nbsp;&nbsp;&nbsp;slope = pm.Normal("slope", mu=0, sigma=1)
&nbsp;&nbsp;&nbsp;&nbsp;intercept = pm.Normal("intercept", mu=0, sigma=1)
&nbsp;&nbsp;&nbsp;&nbsp;σ = pm.HalfNormal("σ", sigma=1)

&nbsp;&nbsp;&nbsp;&nbsp;pm.TruncatedNormal(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"obs",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mu=slope * x + intercept,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sigma=σ,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;observed=y,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lower=bounds[0],
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;upper=bounds[1],
&nbsp;&nbsp;&nbsp;&nbsp;)
&nbsp;&nbsp;return model
</pre>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>I did both of these things now.</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Well spotted. I deleted the whole paragraph as it is no longer true. Not for the user anyway.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>I believe I've done this right. Let me know if not.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Thanks. Have added links to GitHub profile back in.</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>I know what you mean, but I'm not 100% convinced an arrowhead on top of the line there already would be a big improvement. But I can come back to this if you think it's a big deal</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
<p>What about a scatter point with a label "truncation bound"?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by OriolAbril** [comment]
<blockquote>on top of the line there already</blockquote><p>I meant replacing the spiking like by an arrow, like it's done in the example image (copied below). It's not a strong preference though.</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/271/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
Just a quick judge to @OriolAbril if I may? Any strong objections to leaving this as it is?
Screenshot 2022-01-18 at 17 43 14

**Comment by OriolAbril** [comment]
MIssed the previous response. No objections to leaving the plot as it is. 

> but the height of the line/arrow matters, equating to the cumulative density up to the lower bound

Again, no opposition to not updating the plot, we can go ahead and merge the notebook as is. **It already looks like a spike and that is what matters to me**. I do have one nit to add on that comment.

I don't think the quoted comment is true though. I think what matters is the area, not the height (which given the 0 width would be infinite) otherwise the pdf woudn't be normalized anymore right?

Setting the height to the value of the area (as a rule, not in this case where it already looks like a spike) could be confusing (even end up lower than the rest of the pdf!) if you take the (b) subfigure of the image I shared above for example, the area represented in the spike is 0.5 but its height is ~0.75 because otherwise it would probably look to close to the rest of the pdf. Moreover, if sigma of the normal were lower, then the mode would have higher pdf value:

imatge

the same censoring at 0 on the `0, .2` normal would end up with the "spike" way below the pdf, making the censoring not noticeable unless the spike is make higher than its area.

---

After writing that I realize we probably need to update some of the wording on the PR, maybe also the docs? The intuition is still the same: All the probability before/after the bound is _concentrated_ at the bound. But the way to achieve this mathematically is not by setting `pdf(lower)=cdf(lower)` but by adding a delta with that area at the boundary.

**Review by OriolAbril — APPROVED** [review]

**Comment by OriolAbril** [comment]
related to https://github.com/pymc-devs/pymc-examples/issues/90

**Pull request merged**
