### PR TITLE
GP-Latent update for v4

### PR DESCRIPTION
**Pull request by bwengals**
Associated with #72, and is tied to PR in pymc-devs/pymc [#5055](https://github.com/pymc-devs/pymc/pull/5055).  

The notebook was reran using the fixes from the v4 GP branch, so the examples will error if merged before pymc v4 is done.  Also I tried to make the right changes to be aligned with the style guide, but please let me know if I missed anything!

### CODE REVIEW

**Comment by fonnesbeck** [comment]
<p>@bwengals are you able to fix this?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/237/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by fonnesbeck** [comment]
Please re-run the notebook to get rid of the errors in the current render.

**Comment by fonnesbeck** [comment]
The fit is not great on the last model. Maybe boost the tune interval to 2000?

**Comment by fonnesbeck** [comment]
Are you using a bespoke `invlogit` instead of `pm.math.invlogit` because of stability issues?

**Comment by ricardoV94** [comment]
> Are you using a bespoke `invlogit` instead of `pm.math.invlogit` because of stability issues?

If that's the case, check if it is still needed. We have improved invlogit stability in Aesara. Also the Bernoulli can take logit_p directly

**Comment by bwengals** [comment]
So sorry for missing these comments :(  I did finish it up today, hopefully I addressed you guys' comments.  Unfortunately I used the wrong email address for a few previous commits, then made a big git mess trying to change them.  If you guys don't mind, I'm just going to open a new PR tomorrow...

**Comment by bwengals** [comment]
Closing for #371

**Pull request closed without merging**
