### PR TITLE
Adapted code for survival_analysis.ipynb to work with v4

### PR DESCRIPTION
**Pull request by cuchoi**
Updates survival analysis notebook to v4. Issue #128.

+ [ ] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [x] PR description contains a link to the relevant issue: a tracker one for existing notebooks or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by cuchoi** [comment]
The code (new and old) has a very high number of divergences (>100). Would it be worth it to try to reduce that? Although the r_hat values look good, it seems that we shouldn't be encouraging analysis with this level of divergences?

**Comment by canyon289** [comment]
If you can do so but otherwise add a note with a disclaimer that this
amount of divergences would warrant further investigation. it's a good
teaching opportunity!

**Comment by cuchoi** [comment]
Makes sense! I think I will add a disclaimer since I don't know enough about these type of models to get rid of the divergences

**Comment by canyon289** [comment]
Sounds good, and if youd like open up an issue ticket as well so someone else can come by later and try their hand at reducing the divergences

**Comment by twiecki** [comment]
Thanks @cuchoi!

**Pull request merged**
