### PR TITLE
[WIP] Review changes to survival_analysis.ipynb 

### PR DESCRIPTION
**Pull request by olgadk7**
Wanted to submit the incorporated changes recommended in #96: all but the convergence one (looking into it this week). Had to start another branch as the original one had irresolvable conflicts (guessing because of me not submitting often). 

Closes https://github.com/pymc-devs/pymc3/issues/4603, addresses #128

### CODE REVIEW

**Comment by olgadk7** [comment]
@MarcoGorelli, @OriolAbril Regarding the convergence issue, increasing the target_accept does the trick: the number divergences is cut in half, r_hat is 1, the sampler converges, the chains in the forest plot lay snug, and the posterior looks almost exactly the same as in the original notebook. Is that enough for the job at hand or should we reparameterize?

**Review by OriolAbril — APPROVED** [review]
Increasing the target_accept is more than enough for our purposes here. I commented two very minor nits, it could be merged as is once you push the converged results too. 

This is already great, thanks for the PR! I hope it has been an enriching and pleasurable experience

**Comment by olgadk7** [comment]
Yes, enriching and pleasurable, thank you! Contributing is definitely one of the best way to learn, and with your help, support, and patience this was an invaluable experience. I’ll be on the lookout for opportunities to continue participating :)

**Comment by olgadk7** [comment]
Curious, when do the notebooks / code base update to reflect the merged changes? What does it depend on? Thank you.

**Comment by MarcoGorelli** [comment]
Great job @olgadk7 !

The website'll be updated with the next release of PyMC3 (ATM it's not updated after each commit to this repo - but perhaps it should be!)

**Comment by OriolAbril** [comment]
> The website'll be updated with the next release of PyMC3 

And this is a completely manual process which we sometimes forget or do significantly later than the release. :sweat_smile: 

> (ATM it's not updated after each commit to this repo - but perhaps it should be!)

Indeed, it would be amazing to have both release and dev version docs, with the dev version being updated with every commit here, I believe we already have an issue for this.

**Pull request merged**
