### PR TITLE
Correct definition of nu and assign lower value for sigma_low

### PR DESCRIPTION
**Pull request by hyosubkim**
- 1 should be added to nu_minus_one using pm.Deterministic, otherwise addition of 1 in old definition has no effect and hence probability was non-zero for values of nu that are less than one
- Added definition and figure panel for log10(nu) to better align with Kruschke 2013
- Lowered sigma_low value to 10^-1 because sigma values less than 1 are credible (as seen for Group 2 Std Dev in Fig 3 from Kruschke 2013)

With suggested changes, results will more closely align with Kruschke paper, which example is based on.

# {Insert Description}

+ [ ] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [ ] PR description contains a link to the relevant issue: a tracker one for existing notebooks or a proposal one for new notebooks
+ [ ] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by OriolAbril** [comment]
Thanks, can you run pre-commit?

It should be something like:

```
pip install pre-commit # or conda or local install
pre-commit run --all
```

which should update the `.myst.md` file. Then commit and push and all checks should pass hopefully

**Comment by hyosubkim** [comment]
I did as suggested and pushed the changes. Hope it went through okay this time.

**Review by OriolAbril — APPROVED** [review]

**Comment by OriolAbril** [comment]
Thanks! This got both CI jobs to pass

**Comment by hyosubkim** [comment]
Great! Thanks again for your help

**Pull request merged**
