### PR TITLE
Updates to binning case study to work with PyMC v4

### PR DESCRIPTION
**Pull request by cuchoi**
Issue #270 

+ [x] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [x] PR description contains a link to the relevant issue: a tracker one for existing notebooks or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by twiecki** [comment]
Looks like some `myst` problem? Make sure your code is black and then try to remove the myst file so that it will get regenerated during pre-commit.

**Comment by cuchoi** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/366/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cuchoi** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/366/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cuchoi** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/366/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cuchoi** [comment]
<p>Updated the import for the sample code. Also updated <code>at.concatenate</code>  to <code>pm.math.concatenate</code>  and <code>at.exp</code>  to <code>pm.math.exp</code>. Didn't find a <code>pm.math</code> equivalent for <code>at.extra_ops.diff</code>.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/366/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cuchoi** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/366/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cuchoi** [comment]
<p>Updated the text to remove the explanation.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/366/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @cuchoi!

**Pull request merged**
