### PR TITLE
Update GLM predictions

### PR DESCRIPTION
**Pull request by chiral-carbon**
Addresses issue #85 and aims to advance it to best practices, use `arviz-darkgrid` and use `bambi`.

### CODE REVIEW

**Comment by fonnesbeck** [comment]
Is this close to being ready? At this point we should go ahead and convert to v4.

**Comment by chiral-carbon** [comment]
@fonnesbeck Hi, sorry to leave it here without updating. Will work on it this week and finish it up.

**Comment by fonnesbeck** [comment]
@chiral-carbon any chance of pushing this out, or do you want to hand it over to someone?

**Comment by chiral-carbon** [comment]
I'll handle it! If I don't push it out this weekend I'll let you know to
hand it over to someone else

**Comment by chiral-carbon** [comment]
@fonnesbeck should I try to update this to v4 now in this PR or v3 only? and leave v4 upgrade for a new PR? this same question applies to the other open PRs I have pending.

**Comment by cfonnesbeck** [comment]
Definitely v4, as we are trying to get as many examples ported before the v4 release as possible. Let me know if you need a hand!

**Comment by chiral-carbon** [comment]
@cfonnesbeck okay! will need some help in that case. you could just point out what I should refer to/start with, or anything else that should be done first.

**Comment by fonnesbeck** [comment]
It looks like this one is in a bit of a holding pattern until the [update to Bambi](https://github.com/bambinos/bambi/pull/496) is released, but if you want to get a head start you'd have to build Bambi from its `v4` branch, switch from `pymc3` to `pymc` and see what breaks.

**Comment by tomicapretto** [comment]
> It looks like this one is in a bit of a holding pattern until the [update to Bambi](https://github.com/bambinos/bambi/pull/496) is released, but if you want to get a head start you'd have to build Bambi from its `v4` branch, switch from `pymc3` to `pymc` and see what breaks.

@chiral-carbon @fonnesbeck most things should work fine in the new `v4` branch. The problems are related to some specific cases. I can assist if you need help!

**Comment by chiral-carbon** [comment]
@tomicapretto @fonnesbeck thanks! I will update here when as and when I need help

**Comment by drbenvincent** [comment]
This notebook was updated to v4 by #370, so closing this PR

**Pull request closed without merging**
