### PR TITLE
Add HSGP reference and example nb

### PR DESCRIPTION
**Pull request by bwengals**
# HSGP reference and examples

Corresponding to issue #646. The first two examples, for the Basic Usage NB are ready for review 🍾 
NB: needs [this version](https://github.com/pymc-devs/pymc/pull/7335) of PyMC to run

### CODE REVIEW

**Comment by AlexAndorra** [comment]
I've started a review, that I'll push directly to your branch when ready

**Comment by bwengals** [comment]
thanks @AlexAndorra!  Also very open to splitting this up -- it is pretty long, sorry.  That might make it easier to review.

**Comment by fonnesbeck** [comment]
Would be cool to have `approx_params` available as a utility function.

**Comment by fonnesbeck** [comment]
Perhaps emphasize in the text what you are looking for in the gram plots (the bright yellow diagonal)?

**Comment by fonnesbeck** [comment]
Would it be worth having an alias for `_m_star` called something like `num_basis_vectors` as a convenience?

**Comment by bwengals** [comment]
> Perhaps emphasize in the text what you are looking for in the gram plots (the bright yellow diagonal)?

Added this text:

> The plots above compare the approximate Gram matrices to the unapproximated Gram matrix in the top left panel.  The goal is to compare the approximated Gram matrices to the true one (upper left).  Qualitatively, the more similar they look the better the approximation.  Also, these results are only relevant to the context of the particular domain defined by `X` and the chosen lengthscale, $\ell = 3$ -- just because it looks good for $\ell = 3$ doesn't mean it will look good for, for instance, $\ell = 10$.

> Would be cool to have approx_params available as a utility function.

Yah I agree! it'd clean the nb up a bit too.  Any thoughts on a name?  I really don't like how vague "approx_params" is but couldn't think of anything particularly better.

> Would it be worth having an alias for _m_star called something like num_basis_vectors as a convenience?

Definitely, especially now I think it's a good idea that users access it directly sometimes.

**Comment by juanitorduz** [comment]
<p>Can you add a reference to equation (3) in [Practical Hilbert space approximate Bayesian Gaussian processes for probabilistic programming](<a href="https://link.springer.com/article/10.1007/s11222-022-10167-2" target="_blank">https://link.springer.com/article/10.1007/s11222-022-10167-2</a>)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845377'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>What do you mean by "a lower fidelity HSGP approximation" here?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845182'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>I think it's just that the test set in the region where x1 &gt; 2 and x1 &lt; 4</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845206'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done on my version, I'll push it to Bill's branch ASAP</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845250'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>These plots are absolutely beautiful!!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845280'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
I'm (slowly) making my way through this your awesome work @bwengals -- Now moving to reviewing example 3.
I just pushed my edits for the first two sections.
I agree with the addition of `approx_params` and renaming of `m_star`.  Will try to get that done too

**Comment by bwengals** [comment]
<p>What's HDO stand for (though I think I know what you mean)?  Yeah, that's a good idea</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845058'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>you're right this isn't well written.  How about:</p><p> </p><p>Instead of constructing and then directly adding them, the sum of two HSGPs can be computed more efficiently by first taking the product of their power spectral densities, and then creating a single GP from the combined power spectral density.  This reduces the number of unknown parameters because the two GPs can share the same basis set.</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845080'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>hmm, maybe I could say something in text?  A legend for each panel clutters things quite a bit.  The first panel has 3 basis functions, the middle has 3, and the rightmost has 5.  </p><p> </p><p>This actually doesn't line up with the text, which just says there are 3 basis functions per panel.  I'll change it to 3 for all panels.</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845112'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>Oh good point.  What if restrict myself to saying just "basis vector"?  I feel like saying eigenvectors of Dirichlet's Laplacian will only be meaningful to some people.  And if you wanna actually know what that means the papers are the source for that info.  </p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845137'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>I would agree... But, I'm using the notation from the "Practical HSGP" paper, so blame them</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845156'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>You're right @juanitorduz, the differences don't jump out, except for maybe the top right.  You can also see it in the upper left and bottom right blocks on the bottom row.</p><p> </p><p>I agree that matrix norm makes sense, but I don't want to propose any kind of approach here... since I have no idea what norm would be a good cutoff.  And I also don't think this is a widely useful approach anyway because maybe K is too big to calculate directly.  </p><p> </p><p>The goal was more to merely get a feel for whats going on that makes a bad HSGP approximation bad.  And so that would show how someone might start doing some detective work to see if the approximation would be good enough for their particular use case.</p><p> </p><p>@AlexAndorra, I was meaning like, just low fidelty = bad approximation.  The GP approximation is too "compressed" in a sense and so it cant reproduce the true GP.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845182'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>Yup, what Alex said.  This is written nowhere though so I'll add some text for this</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845206'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>@juanitorduz, how do you do that with arviz?  It drives me crazy...  is there a trick or is it super manual?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845250'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>thanks Alex!  the qmc thing is what made them actually look nice.  I think I should probably use a diverging colormap that's white at zero...</p><p> </p><p>RE metrics, I dont know of anything specific to GPs.  Any lack of fit metric?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845280'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>good call, i'll add these.</p><p> </p><p>Also, this figure is rendering absolutely massive in reviewnb, I hope it doesn't look like this in the docs.  Do you know of recommendations for figure sizes in pymc-examples?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845298'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by bwengals** [comment]
<p>I did originally, but changed it to blues so it was comparable to the kronecker example.  </p><p> </p><p>Still makes sense to change it though, but in case you hadnt gotten to the kronecker part yet, what do you think in that context?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845314'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>HDI 🤪</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845058'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>I think this version is clearer. You can think about adding this into a little box so that users see it as a side remark </p><p> </p><p><code></code><code></code><code></code>{admonition} Adding to HGSPs</p><p>Instead of constructing and then directly adding them, the sum of two HSGPs can be computed more efficiently by first taking the product of their power spectral densities, and then creating a single GP from the combined power spectral density. This reduces the number of unknown parameters because the two GPs can share the same basis set.</p><p><code></code><code></code><code></code></p><p> </p><p>See <a href="https://jupyterbook.org/en/stable/content/content-blocks.html" target="_blank">https://jupyterbook.org/en/stable/content/content-blocks.html</a></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845080'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>basis vector seems good! </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845137'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>ahaha ok XD</p><p> </p><p></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845156'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>I think both suggestions will improve this :</p><p>- lower m and c a touch to make them worse</p><p>-  Add explanation in the text where to focus concretely</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845182'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Yes: I always use this code to plot traces / rank plots:</p><p> </p><p><span class="ql-cursor">﻿</span>axes = az.plot_trace(</p><p>    data=idata_1,</p><p>    var_names=var_names,</p><p>    compact=True,</p><p>    kind="rank_bars",</p><p>    backend_kwargs={"figsize": (15, 17), "layout": "constrained"},</p><p>)</p><p>plt.gcf().suptitle("Trace - Model 1", fontsize=16)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845250'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>This was more of a question (outside the scope of the notebook) XD</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845280'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>I usually create figures as </p><p> </p>

<pre class="ql-syntax" spellcheck="false">s = pm.draw(pm.Lognormal.dist(mu=0.5, sigma=0.5), draws=10_000)

fig, ax = plt.subplots(figsize=(10, 6))
ax.hist(s, np.linspace(0, 5, 100));
</pre>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845298'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>This way you can specify the sizes directly</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845298'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>Right! after the &nbsp;kronecker part this makes sense. No strong opinion here. Both work together.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845314'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
<p>ah ok! thanks for the clarification :)</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845377'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>I handled that in the version I'm working on @Bill</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845298'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>That being said, I don't think this particular plot is useful, I'd remove it. Which point are you tring to convey?</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845298'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>+1</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845343'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Can you copy the PyMC implementation and spot out the changes you made, to make them more explicit? I think it'd help understanding</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845377'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Agreed, I'll add that.</p><p>Also @Bill, I think you should add an explanation as to why you're doing this:</p><p><code>log_ell_delta = log_ell_mu + log_ell_delta_sd * log_ell_delta_z</code></p><p>Otherwise it comes as a bit of a surprise in the code</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018940995'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845432'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845465'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Why don't <code>eta</code> and <code>ell</code> entrer this computation?  </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018941014'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Agreed, I got lost too. I think it's also worth to spot where (and why) the computation differs from the custom PSD computation in the previous example</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018941070'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Do you think we can / need to detail the idea of Kronecker structure a bit more @Bill?</p><p>I feel like this version goes a bit too fast</p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845477'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018941084'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845500'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018941104'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Just pushed the latest version. Here is the TODO before we can merge:

- [ ] Fix the posterior predictive sampling bug in example 3. We're working on that with @bwengals, and that's a sneaky one... Still don't know if it's due to `sample_posterior_predictive` or a bug in the computation of `phi` (the GP basis vectors).
- [ ] Split into two NBs: Examples 1 and 2 for a Basic Usage NB, and examples 3 and 4 for an Advanced Usage NB
- In pm.gp.HSGP: 
  - [ ] `parametrization` is not documented
  - [ ] Add option to pass in nicely named `coords` to HSGP for the `beta` coefficients
  - [ ] Make `._m_star` more accessible / user friendly (make a property with no leading underscore so existing code doesn't break), document it, and fix example in `prior_linearized` docstring.
  - [ ] Get rid of numpy option, `tl=np`.  It's subtly wrong when calculating the eigen stuff and its not used anywhere.
  - [ ] Move the `approx_params` function to `hsgp_approx` file, so take it out of the NB here and think of a better name

Will comment here as we get through it

**Comment by fonnesbeck** [comment]
Is it worth adding this more or less as-is, and then iterating on it later? Would be good to have this out there.

**Comment by juanitorduz** [comment]
+1 on pushing this one soon-ish and iterate (hopefully also https://github.com/pymc-devs/pymc-examples/pull/627 which needs the last ✅ 🙏 )

**Comment by AlexAndorra** [comment]
Yeah I’ll work on getting the first part out asap. It’s done already — the
blocking point is the bug in predictions, which I’m still investigating.
But that’s in the second part. I’ll ping you guys for review

Il giorno gio 25 apr 2024 alle 15:07 Juan Orduz ***@***.***>
ha scritto:

**Comment by AlexAndorra** [comment]
Any rush on your end BTW @fonnesbeck @juanitorduz ? There is a project I'd like to finish first, so checking my priorities

**Comment by juanitorduz** [comment]
No rush from my side :)

**Comment by AlexAndorra** [comment]
FYI, I'll have the first NB (Examples 1 and 2 for Basic Usage) ready by end of next week

**Comment by AlexAndorra** [comment]
FYI: I'm almost there for the first notebook -- just need to move around a last roadblock. Hopefully this week

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845206'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845250'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845036'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845058'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845080'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2018845182'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
The first two examples, for the Basic Usage NB are ready for review @fonnesbeck @juanitorduz @bwengals  🍾 
NB: needs [this version](https://github.com/pymc-devs/pymc/pull/7335) of PyMC to run

**Comment by juanitorduz** [comment]
@AlexAndorra This looks great! I left some minor suggestions. I think it would be nice to follow the style guide that suggests direct link to the PyMC classes and methods (e.g. {class}`~pymc.gp.HSGP` and {class}`~pymc.gp.HSGPPeriodic` ). You can copy-paste from https://github.com/pymc-devs/pymc-examples/pull/627/files#diff-57b0768a7c3030b2c07ad2f8a05d0436c41db8fd7e73303876917a9ac6a5aaff some of these methods (or modify them)

**Comment by AlexAndorra** [comment]
<p>Do I <em>have</em> to do that? I personally <em>really</em> dislike this syntax and try to avoid it as much as possible 🙈</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2132968099'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Thanks @juanitorduz ! On it right now.

Question though:
> direct link to the PyMC classes and methods (e.g. {class}~pymc.gp.HSGP and {class}~pymc.gp.HSGPPeriodic )

Isn't that what I did already? Note that I'm really not versed into this syntax (I really dislike it, so there is a high chance my question is stupid)

**Comment by juanitorduz** [comment]
<p>hehe ok! I do not think this is a strong requirement .</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2132968099'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
> Thanks @juanitorduz ! On it right now.
> 
> Question though:
> 
> > direct link to the PyMC classes and methods (e.g. {class}~pymc.gp.HSGP and {class}~pymc.gp.HSGPPeriodic )
> 
> Isn't that what I did already? Note that I'm really not versed into this syntax (I really dislike it, so there is a high chance my question is stupid)

I do not think so. For example, you have:

 The `HSGP` class is compatible ...

but it would be nice to have 

The {class}`~pymc.gp.HSGP` class is compatible ...
 
 so that the link is clickable so that the user can get into the class definition in the PyMC doc. See for example, the raw file https://raw.githubusercontent.com/pymc-devs/pymc-examples/main/examples/gaussian_processes/GP-Births.myst.md where you can see how the classes are written so that they are clickable as in https://www.pymc.io/projects/examples/en/latest/gaussian_processes/GP-Births.html
 
 I do not think this is a blocker. But is very useful for reference and tutorial notebooks ;)

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2132968122'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2132968141'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>I think I've done it, but please make sure to check, as it's really hard to know what the result will be with that syntax 🙏</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2132968157'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2132968186'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Yes, x1, the one on the y-axis</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2132968202'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
<p>Mmmmh, here I think it's a bit too big for a tip actually, especially since I'd say it's something we'd like people to read, not ignore as a "nice-to-know"</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2132968235'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by AlexAndorra** [comment]
Thanks a lot for the quick reviews @juanitorduz 🥳 
Just pushed another round of changes. LMK what you think :)

**Comment by juanitorduz** [comment]
<p>It worked! See <a href="https://pymcio--647.org.readthedocs.build/projects/examples/en/647/gaussian_processes/HSGP-Basic.html" target="_blank">https://pymcio--647.org.readthedocs.build/projects/examples/en/647/gaussian_processes/HSGP-Basic.html</a></p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/647/discussion/#comment-2132968157'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
The class reference worked! See 

image

https://pymcio--647.org.readthedocs.build/projects/examples/en/647/gaussian_processes/HSGP-Basic.html

I think it would be nice to have the same syntax in the intro, as is the first entry point of these classes. 

image

Besides this, it looks great!

**Review by juanitorduz — APPROVED** [review]

**Comment by AlexAndorra** [comment]
Just reran the NB with the latest changes of the [PR on the PyMC repo](https://github.com/pymc-devs/pymc/pull/7335). Actually, let's wait for this PR to be merged before merging that one

**Comment by AlexAndorra** [comment]
Just merged #7335 @juanitorduz , we can merge this one 🥳 
Now focusing on solving the bug in prediction for the second tutorial

**Comment by juanitorduz** [comment]
Fantastic work @AlexAndorra !

**Pull request merged**
