### PR TITLE
Rerun glm-logistic

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Use inferencedata / ArviZ

---

This one took 9668.2s on Kaggle kernels with GPU!

### CODE REVIEW

**Comment by twiecki** [comment]
@MarcoGorelli What's missing here?

**Comment by MarcoGorelli** [comment]
I think there's a few errors, but I plan to address them this week

**Comment by OriolAbril** [comment]
related to https://github.com/pymc-devs/pymc-examples/issues/82

**Comment by MarcoGorelli** [comment]
closing as stale for now as I'm never getting round to this and there are other PRs addressing glm notebooks anyway

**Pull request closed without merging**
