### PR TITLE
notebook: Bayes Factor; run using pymc v5

### PR DESCRIPTION
**Pull request by reshamas**
# Description
Run Bayes Factor notebook with PyMC version 5.

NOTE:  needed to set `progressbar=False` to avoid errors.

### CODE REVIEW

**Comment by cluhmann** [comment]
Is there an issue open for the progressbar problem?

**Comment by reshamas** [comment]
> Is there an issue open for the progressbar problem?

No. @OriolAbril said it was specific to this notebook, not a general problem.

**Comment by OriolAbril** [comment]
There is an issue: https://github.com/pymc-devs/pymc/issues/5855 we already commented there, but it is not clear how to reproduce the issue so it hasn't been fixed.

**Comment by cluhmann** [comment]
Got it.  Just wanted to make sure it was being referenced here if the issue already existed.  But now it is!

**Comment by OriolAbril** [comment]
I have re-executed the notebook locally to see if I could reproduce the issue, but I didn't, in my case it worked, so the issue will continue to be open and with no solution in sight. I have pushed so we can merge without needing to remove the progressbar in sample_smc

**Review by OriolAbril — APPROVED** [review]

**Pull request merged**
