### PR TITLE
Longitudinal models

### PR DESCRIPTION
**Pull request by NathanielF**
# Example Notebook on Longitudinal Analysis and Growth Curve Trajectories. 

Related to this issue: https://github.com/pymc-devs/pymc-examples/issues/508

+ [X] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [x] PR description contains a link to the relevant issue:
  * a tracker one for existing notebooks (tracker issues have the "tracker id" label)
  * or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

Example of iterative model construction on longitudinal data following the Willett and Singer book. In the first model we follow the text quite closely, and in the second model we choose an alternative likelihood model and fully difrerent set of priors.

### CODE REVIEW

**Comment by NathanielF** [comment]
I think this is close to done now. Tagging @aloctavodia and @drbenvincent since you both expressed an interest in the topic. 
The broad structure of the notebook is as follows: 

image

I focus on 2 examples of iterative model building and the extraction of the within-individual and across-individual trajectories of growth learned by the model. I've tried to explain the crucial aspects of the model as i understand them without getting too caught up in the confusing vocabulary of fixed and random effects, so i'd be grateful for feedback on this aspect especially. I don't want to add to the confusion around these terms!

In the first example i follow the textbook very closely using a normal likelihood and derive parameter estimates akin to those reported in the text. In the second example i go off-reservation and use a gumbel likelihood with censoring which looks more appropriate to me than the Normal likelihood they were constrained to use in the text.  I also briefly call out that you can (and probably should) use Bambi for these kinds of models where possible.

**Comment by drbenvincent** [comment]
Sorry for slow response @NathanielF. Fingers crossed I'll have time to review this weekend, or early next week.

**Comment by NathanielF** [comment]
Giving this one another nudge in case Friday is a good day for this review @drbenvincent?

**Review by drbenvincent — CHANGES_REQUESTED** [review]
Looks great! So far I've just given a wave of style-based comments so things can keep moving. Feel very free to request re-review and I'll focus more on content and clarity.

**Comment by NathanielF** [comment]
<p>Amended</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958600'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Yeah, i don't need the blackjax sampler. Removed now. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958603'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted this now to be more explicit that the bambi section is a digression to explain an alternative method. Capitalised Bayesian too</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958606'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958609'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Hidden</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958611'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>hidden</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958615'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>hidden</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958617'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>adjusted. Note one concern here is the color formatting renders differently to color the whole line rather than just the symbols on the site.</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958622'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Hidden</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958625'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958630'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>hidden</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958637'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>hidden</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958639'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958650'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>adjusted</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958645'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by drbenvincent — CHANGES_REQUESTED** [review]
Just a few minor style issues:
- For the multi-line equation block where we have the align environment, if you place the $ symbol before the = or ~ then everything aligns to that. At the moment it's right aligned.
- Add `time series` to the tags
- Consider moving from the Case Studies section to the Time Series section of the repo
- Missing space after full stop for "our model.The"
- Remove commented out line... `# grade = pm.MutableData('grade_data', df_external['GRADE'].values)`
- Ideally, it would be possible to suppress console output after plotting with `;`. But I can't remember if the black formatting removes that. I believe there's a way to suppress black from removing that
- Where you do use `sample_numpyro_nuts`, can you use the `hide-output` (cell tag) because we get a whole bunch of progress bar output that we don't need. Or maybe there's a specific kwarg for that sampler to suppress that?
- In the rendered website output, there's something really broken about the rendering of the L2 Watermark header, after the References L2 header. I've not double checked, but can probably be fixed by having that in it's own cell. Either way, there's something not working there. More info here https://www.pymc.io/projects/docs/en/latest/contributing/jupyter_style.html#watermark

**Comment by NathanielF** [comment]
<p>Done. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/520/discussion/#comment-1464958627'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
Nice. I'll endeavour to do a final pass, reviewing content/clarity in the next few days and we can ship this :) Do feel free to ping me, but it is on my list.

**Comment by NathanielF** [comment]
> Consider moving from the Case Studies section to the Time Series section of the repo

On this point, i think i prefer it in the case studies section. Time series analysis/modelling is (in my head anyway) a different kind of beast than longitudinal curve analysis. They're clearly, related... but just not the same bucket for me. Can move it if you feel strongly about it, but i prefer it as it is. 

On the watermark thing i wasn't sure what you meant... it looks ok to me: 

image

**Comment by NathanielF** [comment]
> Nice. I'll endeavour to do a final pass, reviewing content/clarity in the next few days and we can ship this :) Do feel free to ping me, but it is on my list.

Perfect. Thanks for your help on this!

**Comment by NathanielF** [comment]
Just a small nudge @drbenvincent.

**Review by drbenvincent — COMMENTED** [review]
Could you add a coord for the observations for all models. We have 246 in the early models, and 254 with later models.

**Comment by drbenvincent** [comment]
Typo in this sentence "Implementing the model is PyMC is as follows"

**Comment by drbenvincent** [comment]
I'm wondering if we could get the model math for the "The Uncontrolled Effects of Parental Alcoholism" model. Don't worry about the colour coding if that gets messy.

**Comment by drbenvincent** [comment]
After this sentence 

> The formula specification uses 1 to denote an intercept term and a conditional | operator to denote a subject level parameter combined with the global parameter of the same type in the manner specified above.

could you just spell out how to read the hierarchical term `(1 + age_14 | id)` in the Bambi model equation

**Comment by drbenvincent** [comment]
I think there's one instance of a lower case "bambi", but everything else is capitalised.

This is great. Happy to approve after these minor tweaks 👍
Sorry for the delay in finishing the review

**Comment by NathanielF** [comment]
Thanks @drbenvincent! Will get to these tonight.

**Comment by NathanielF** [comment]
Made those changes @drbenvincent. Seemed to work in the Review Notebook, but docs build check renders strangely: 
Seems to effect all notebooks, so likely something to do with the broader site render than my specific PR here. 

image

**Review by drbenvincent — APPROVED** [review]
So the formatting issue looks like a broader issue, not something specific to this notebook. So happy to approve. Let me know if there are any minor tweaks you wanted to make, otherwise I'll merge.

Thanks again for the contribution, and for bearing with the tardy reviews.

**Comment by NathanielF** [comment]
Happy with it. Feel free to merge! Thanks again

**Pull request merged**
