### PR TITLE
Moderation analysis example

### PR DESCRIPTION
**Pull request by drbenvincent**
Hi all
Here's a pull request adding an example notebook covering moderation analysis.  I wasn't quite sure on the policy of where to store an embedded image, so I've just included one in the directory that the notebook is in. Just let me know if you need any changes made.

### CODE REVIEW

**Comment by ricardoV94** [comment]
This is really neat! The visualizations with the moderator variable really speak for themselves. 

I left some minor comments if you want to address them :)

**Comment by drbenvincent** [comment]
Thanks @ricardoV94, I should be able to deal with these points soon.

**Comment by fonnesbeck** [comment]
This is great, thank you. The data import should probably use `pm.get_data`, rather than a relative path string.

**Comment by drbenvincent** [comment]
Excuse the slight delay... I had to get a couple of papers submitted. I believe I've not implemented all the changes asked for. The last changes were to provide `idata_kwargs` when sampling, which enabled use of xarray, which has meant I could kill a utility function to extract samples which has lead to smoother plotting code. Let me know if there's anything else :)

**Comment by drbenvincent** [comment]
Thanks for those points @OriolAbril. Unless anyone has any further things, I think that might be it. 🤞🏼

**Review by OriolAbril — APPROVED** [review]
Thanks for the PR! I'll happily add this notebook directly to the "Best Practices" column

**Pull request merged**
