### PR TITLE
Frailty survival model

### PR DESCRIPTION
**Pull request by NathanielF**
# Frailty Models - Hierarchical Survival Models

Related to this issue: https://github.com/pymc-devs/pymc-examples/issues/579

Leaving as Draft for now. 

+ [x] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [X] PR description contains a link to the relevant issue:
  * a tracker one for existing notebooks (tracker issues have the "tracker id" label)
  * or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

----
:books: Documentation preview :books:: https://pymc-examples--580.org.readthedocs.build/en/580/

### CODE REVIEW

**Comment by NathanielF** [comment]
<p>In the case of the CoxPH regression the "Poisson trick" is a classic of the literature and it works to give me the results i was expecting. It's also consistent with the approach already documented in Austin's notebook. </p><p> </p><p>More generally in the case of the AFT models below. I tried using the pm.Censored with the Weibull regression, but it gave me garbage results and was allot slower than using the Potential. And again in the case of the Weibull AFT my current parameterisation gives the expected results. </p><p> </p><p>But maybe i'm missing something, was there a pattern of usage you had in mind w.r.t. to using censored liklihoods for survival?</p><p> </p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1752188864'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ricardoV94** [comment]
> But maybe i'm missing something, was there a pattern of usage you had in mind w.r.t. to using censored likelihoods for survival?

From a first glance it sounded like you just wrote your own Censored likelihood by hand. Since we implemented it in PyMC we've been moving examples towards using the Censored factory instead because that fits much more with the PyMC vibe. Similarly, nobody is writing Potentials for Mixture likelihoods either, because we have pm.Mixture).

I imagine Austin example predates pm.Censored?

**Comment by ricardoV94** [comment]
> More generally in the case of the AFT models below. I tried using the pm.Censored with the Weibull regression, but it gave me garbage results and was allot slower than using the Potential. 

I was talking about this one yes, not the Poisson trick. Sounds like a bug or a different parametrization of the Weibull than what you're comparing against. Using pm.Censored could be slower but shouldn't give different results. It's literally just doing what you did with the Potential.

**Comment by NathanielF** [comment]
Can you show me an example of how to use the censored distribution for AFT models. This is what i tried....
image

**Comment by NathanielF** [comment]
> I am not familiar with the Poisson trick. Google didn't elucidate it quickly for me.

See maybe here: https://cran.r-project.org/web/packages/survival/vignettes/approximate.pdf
Also, in a textbook i have at home...

**Comment by ricardoV94** [comment]
In that example you didn't pass observed.

When you have mixed censored and not censored you have to pass an array to `upper` with `+inf` for the uncensored obs and y for the censored ones. Something like

`pm.Censored("obs", dist, lower=None, upper=np.where(cens, y, +inf), observed=y)`

**Comment by NathanielF** [comment]
Ah... i did miss observed... but now i just get a crash out: 
image

image

Similar crashes for different upper bounds

**Comment by ricardoV94** [comment]
Maybe try `upper=np.where(cens, y, y+1)`. The last value has to be larger than the observations when they are not censored. np.inf could be leading to numerical issues in the logcdf

**Comment by ricardoV94** [comment]
Your `upper` is still weird. Do you have a constant censoring at `y=20`? If that's the case you should just be able to set `upper=20`

`upper` is the point of truncation. You are not allowed to observe any value beyond upper. If it matches exactly with `upper` it means that observation was censored. If it is below, it was not censored. `upper=np.where(cens, y+1, 20)` is odd. It say for the cases where `cens` is True, the censoring point is y+1 (which means it won't be treated as censored in the logp), otherwise it's 20.

**Comment by NathanielF** [comment]
Ugh, sorry. Don't know where my head is this morning!

**Comment by ricardoV94** [comment]
Just as a sanity check do you get a -inf logp at the starting point if you just use a normal Weibull (without censoring). I wonder if the PyMC parametrization is just different than what you were working with.

**Comment by NathanielF** [comment]
You mean, just run the observed like this: 
image

Seems to run fine

**Comment by ricardoV94** [comment]
No, rut it with all observations, censored and non-censored as if they were all uncensored

**Comment by NathanielF** [comment]
Seems to run just fine with all observations: 
image

**Comment by ricardoV94** [comment]
Interesting, that suggests a precision issue with the CDF (or a bug in the CDF). Can you open a GitHub issue with a minimal reproducible example, where `model.point_logps()` returns -inf?

**Comment by NathanielF** [comment]
@ricardoV94 added the issue here: https://github.com/pymc-devs/pymc/issues/6946

**Comment by NathanielF** [comment]
Marking this as ready for review. I think i solved the issue translating between the Logistic model fit and the log-logistic survival curve i wanted to estimate. Still have a few additional touches, such as adding the references and tidying a conclusion but i thought i'd open it up for review now. 

As stated in the issue the broad idea of this MR is to demonstrate with a more detailed example how to actually build and use the survival regression models in PyMC. In particular i wanted to show how we can add hierarchical components to model individual heterogeneity in the survival functions using the so paradigm of "frailty" models.

**Comment by NathanielF** [comment]
Would be good to get some feedback on the content of this MR at this point. Any interest: @ricardoV94 , @OriolAbril or @AustinRochford ?

**Comment by NathanielF** [comment]
<p>Tried this. Doesn't seem to work</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483644'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483083'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted! </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483135'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483152'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Changed this</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483169'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483235'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted and added note </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483245'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted and clarified. Used pseudo math with formula syntax as it seemed clearest. </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483292'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Added all coordination and dims</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483326'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Clarified</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483424'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483505'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Clarified</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483534'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Changed this. Good call!</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483560'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Changed</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483578'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted and clarified</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483625'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Added all coords</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483662'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483484'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Fixed</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483607'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483681'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Adjusted</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483458'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Added</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483345'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Thanks so much for the detailed feedback! </p><p> </p><p>I think I've addressed all the above comments and it's much stronger now.</p>

**Comment by NathanielF** [comment]
<p>Indeed! </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483711'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
<p>Replaced with print statement </p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483644'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by NathanielF** [comment]
I'm happy with this now! Caught a few extra typos and mistakes in the writing, but basically the same with adjustments for your feedback @drbenvincent. Thanks again for the detailed review!

**Comment by NathanielF** [comment]
Just giving this another nudge @drbenvincent . If you have time it'd be great to get it over the line this week.

**Comment by drbenvincent** [comment]
<p>"In the context of a failure modelling" -&gt; "In the context of failure modelling"</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483209'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Thanks</p>

---

 <a href='https://app.reviewnb.com/pymc-devs/pymc-examples/pull/580/discussion/#comment-1812483644'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
Found a typo "strucuture"

**Comment by drbenvincent** [comment]
It could be worth clarifying this is Wilkinson notation?
Screenshot 2023-11-28 at 15 22 42

**Comment by drbenvincent** [comment]
I'm not sure what I feel about this, but I'm wondering if in this case of utility functions we might want to add type hints just to help the reader out a bit

```python
def cum_hazard(hazard):
    return hazard.cumsum(dim="intervals")


def survival(hazard):
    return [np.exp](https://numpy.org/doc/stable/reference/generated/numpy.exp.html#numpy.exp)(-cum_hazard(hazard))


def get_mean(trace):
    return trace.mean(("draw", "chain"))
```

**Comment by drbenvincent** [comment]
Missing capitalisation. Doesn't follow on from a previous unfinished sentence.

> "which allows us to pull out the gender specific..."

Same here:

> which suggests that the model over

**Comment by drbenvincent** [comment]
Cool! Have added a set of comments above. Mostly small grammatical or stylistic things. Great addition to the set of examples.

**Comment by NathanielF** [comment]
Thanks @drbenvincent, addressed those notes! Pleased with this one.

**Review by drbenvincent — APPROVED** [review]
Nicely done

**Comment by NathanielF** [comment]
Thank you Ben! Appreciate it!

**Pull request merged**
