### PR TITLE
Update Hierarchical binomial notebook

### PR DESCRIPTION
**Pull request by farhanreynaldo**
Updated the GLM hierarchical binomial notebook with the following improvements:

* Fix filename, from `binominal` to `binomial`
* Remove unused imports
* Standardize PyMC3 spelling
* Add BDA3 references
* Fix several typos
* Suppress plot code line

Addresses issue https://github.com/pymc-devs/pymc-examples/issues/247 and issue  #61 

Need to update the authors section, but I don’t know how to trace all the authors who have contributed to this notebook.

### CODE REVIEW

**Review by OriolAbril — COMMENTED** [review]
you also have to update https://github.com/pymc-devs/pymc-examples/blob/main/examples/table_of_contents_examples.js

**Comment by farhanreynaldo** [comment]
> View / edit / reply to [this conversation](https://app.reviewnb.com/pymc-devs/pymc-examples/pull/248/discussion/) on ReviewNB
> 
> _OriolAbril commented on 2021-11-12T13:03:41Z_ ----------------------------------------------------------------
> 
> * Adapted from chapter 5 of Bayesian Data Analysis 3rd Edition {cite:p}gelman2013bayesian by Demetri Pananos and Junpeng Lao ([pymc#3054](https://github.com/pymc-devs/pymc/pull/3054))
> * Reexecuted by Ravin Kumar ([pymc#3397](https://github.com/pymc-devs/pymc/pull/3397))
> * Reexecuted by Alex Andorra and Michael Osthege ([pymc#3955](https://github.com/pymc-devs/pymc/pull/3955))
> * Updated and reexecuted by Raúl Maldonado ([pymc-examples#24](https://github.com/pymc-devs/pymc-examples/pull/24), [pymc-examples#45](https://github.com/pymc-devs/pymc-examples/pull/45) and [pymc-examples#147](https://github.com/pymc-devs/pymc-examples/pull/147))
> 
> (plus correct formatting with section, add yourself...)
> 
> Not yet sure if reexecuting the notebook only should get people listed in the post directive (and therefore in the citation). I don't want to diminish the contribution but don't want to end up having people reexecute notebooks with every minor version only to appear there (not sure that would happen but could be a hacktoberfest goal maybe?)

How should we proceed on this matter, regarding the people listed in the post directive?

**Comment by martinacantaro** [comment]
<p>Hi Reynaldo, thank you for your work on this notebook. Let's only list people who edited the notebook as authors. This would include your contributions, so feel free to add yourself to the list!</p>

**Comment by OriolAbril** [comment]
Can you also add the epilogue as shown here: https://pymc--5059.org.readthedocs.build/en/5059/contributing/jupyter_style.html#epilogue?

**Comment by farhanreynaldo** [comment]
> Hi Reynaldo, thank you for your work on this notebook. Let's only list people who edited the notebook as authors. This would include your contributions, so feel free to add yourself to the list!

Sure, I will update the authors section and the post directive accordingly.

**Comment by OriolAbril** [comment]
I now see that reviewnb messed up the formatting in my comment: `{cite:p}gelman2013bayesian` should instead be `` {cite:p}`gelman2013bayesian` `` otherwise it is not rendered correctly: https://pymc-examples--248.org.readthedocs.build/en/248/generalized_linear_models/GLM-hierarchical-binomial-model.html#authors. Can you also add a section title right before the watermark cell and rebase with main for the citation info to be included already in the preview?

**Comment by farhanreynaldo** [comment]
> It looks like you need to run pre-commit to include the functions used as tags: https://github.com/pymc-devs/pymc-examples/runs/4214798868?check_suite_focus=true#step:4:73

I just realized the pre-commit helps to create tags for the notebook. I have updated it on the latest commit.

**Review by OriolAbril — APPROVED** [review]

**Comment by OriolAbril** [comment]
Thanks again @farhanreynaldo!

**Pull request merged**
