### PR TITLE
Add case study for Bayesian A/B Testing

### PR DESCRIPTION
**Pull request by tcuongd**
## Description

Hi! I'd like to add a case study notebook to provide an introduction to A/B test analysis with Bayesian models. The models implemented are based on [this paper](https://vwo.com/downloads/VWO_SmartStats_technical_whitepaper.pdf). Super keen for feedback / whether or not you think this is useful to add to the examples directory.

If you guys find it interesting, I'm keen to write more notebooks to go into more complicated topics like early stopping of A/B tests, power analyses, and more complex models and priors. I think there's a lot of practical context here beyond the usual textbook examples that would be valuable to readers working in online software.

### CODE REVIEW

**Comment by twiecki** [comment]
Thanks @tcuongd! Bayesian AB testing is a super common use case for pymc3 but so far there were no case studies so this is super relevant. Definitely interested in more in-depth stuff.

**Comment by ericmjl** [comment]
Nice stuff, @tcuongd :smile:. Just one comment from me, above!

**Comment by tcuongd** [comment]
Thanks for the feedback guys :) I've changed the introduction to show a clearer link between A/B testing and controlled experiments.

I've also fixed some bugs with the revenue model example.

Thanks!

**Comment by OriolAbril** [comment]
The notebook is great, and further notebooks on the topic would be amazing :rocket:

**Comment by tcuongd** [comment]
@OriolAbril Could you please take another look? Thank you!

**Comment by tcuongd** [comment]
> They would probably also benefit from a couple sentences restating how the model retrieves the less but larger purchases.

Ah side-by-side is a good idea, and I didn't know you could do that directly with `az.plot_posterior`, nice! I've made the changes :)

**Review by OriolAbril — APPROVED** [review]
That last comment is a very minor nit. IMO, it can be merged right after it's fixed, everything else looks great

**Comment by tcuongd** [comment]
> That last comment is a very minor nit. IMO, it can be merged right after it's fixed, everything else looks great

Thanks Oriol! Have fixed :)

**Pull request merged**
