### PR TITLE
Fix typos in examples

### PR DESCRIPTION
**Pull request by hectormz**
# Fix typos in example notebooks

This PR fixes typos found in the `pymc` example notebooks (mostly in markdown cells, some comments)

+ [X] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [ ] PR description contains a link to the relevant issue: a tracker one for existing notebooks or a proposal one for new notebooks
+ [X] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

### Helpful links
* https://github.com/pymc-devs/pymc-examples/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by hectormz** [comment]
Assuming Myst markdown is like other markdown, maintenance would be much easier if the markdown cells used semantic line breaks

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
@hectormz These are great -- thanks! Did you use a tool for this?

**Comment by hectormz** [comment]
Thanks @twiecki ! I semi-manually used `codespell`.
You can either use it to generate a list of likely misspellings and suggested changes (which I used here because I wanted to look closely)
or it can automatically change the misspellings (if it is confident about the change), which you can approve when staging in git.

I ran it against the synced markdown files (with some skipped strings after `-L` flag) because it picks up the binary blobs in `.ipynb` files:
```
codespell myst_nbs -L hist,fpr,fro,lik
```
Are you interested in adding an automated check to `pre-commit`?

**Comment by canyon289** [comment]
@hectormz can you share the steps? Perhaps we can add this to our linter for notebooks which would be amazing

**Comment by hectormz** [comment]
@canyon289 Added it to `pre-commit`. I'm fairly sure the check will only be useful/work if the `jupytext` sync already passed. But that's fine.

**Comment by OriolAbril** [comment]
something strange is happening with an encoding or something, see https://readthedocs.org/api/v2/build/16957867.txt and readthedocs is unable to generate and publish the docs. We need to fix this before merging.

**Comment by hectormz** [comment]
@OriolAbril at first jupytext was changing line endings for me. Looks like I missed a file. Repulsed. Hopefully that does it

**Comment by twiecki** [comment]
```
reading sources... [ 33%] gaussian_processes/GP-MaunaLoa2
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/case_studies/BEST.ipynb:40002: WARNING: Non-consecutive header level increase; H1 to H3 [myst.header]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/case_studies/bayesian_ab_testing.ipynb:30004: WARNING: Document headings start at H4, not H1 [myst.header]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/case_studies/bayesian_ab_testing.ipynb:40002: WARNING: Document headings start at H3, not H1 [myst.header]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/case_studies/bayesian_ab_testing.ipynb:300002: WARNING: Document headings start at H3, not H1 [myst.header]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/case_studies/bayesian_ab_testing.ipynb:390002: WARNING: Document headings start at H3, not H1 [myst.header]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/case_studies/bayesian_ab_testing.ipynb:630002: WARNING: Document headings start at H3, not H1 [myst.header]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/case_studies/bayesian_ab_testing.ipynb:630019: WARNING: Document headings start at H3, not H1 [myst.header]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/gaussian_processes/GP-MaunaLoa.ipynb:60002: WARNING: skipping unknown output mime type: application/vnd.bokehjs_load.v0+json [mystnb.unknown_mime_type]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/gaussian_processes/GP-MaunaLoa.ipynb:120002: WARNING: skipping unknown output mime type: application/vnd.bokehjs_exec.v0+json [mystnb.unknown_mime_type]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/gaussian_processes/GP-MaunaLoa.ipynb:150002: WARNING: skipping unknown output mime type: application/vnd.bokehjs_exec.v0+json [mystnb.unknown_mime_type]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/gaussian_processes/GP-MaunaLoa.ipynb:180002: WARNING: skipping unknown output mime type: application/vnd.bokehjs_exec.v0+json [mystnb.unknown_mime_type]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/gaussian_processes/GP-MaunaLoa.ipynb:270002: WARNING: skipping unknown output mime type: application/vnd.bokehjs_exec.v0+json [mystnb.unknown_mime_type]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/gaussian_processes/GP-MaunaLoa.ipynb:290002: WARNING: skipping unknown output mime type: application/vnd.bokehjs_exec.v0+json [mystnb.unknown_mime_type]
/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/checkouts/321/examples/gaussian_processes/GP-MaunaLoa.ipynb:330002: WARNING: skipping unknown output mime type: application/vnd.bokehjs_exec.v0+json [mystnb.unknown_mime_type]

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/myst_nb/sphinx_.py", line 143, in parse
    mdit_renderer.render(mdit_tokens, mdit_parser.options, mdit_env)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/myst_parser/docutils_renderer.py", line 217, in render
    self._render_tokens(list(tokens))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/myst_parser/docutils_renderer.py", line 196, in _render_tokens
    self.rules[f"render_{child.type}"](child)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/myst_nb/core/render.py", line 189, in render_nb_cell_code
    self._render_nb_cell_code_outputs(token, outputs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/myst_nb/sphinx_.py", line 275, in _render_nb_cell_code_outputs
    _nodes = self.nb_renderer.render_mime_type(
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/myst_nb/core/render.py", line 551, in render_mime_type
    return self.render_image(data)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/myst_nb/core/render.py", line 625, in render_image
    data_bytes = a2b_base64(data.content)
binascii.Error: Invalid base64-encoded string: number of data characters (946073) cannot be 1 more than a multiple of 4

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pymc-examples/envs/321/lib/python3.8/site-packages/myst_nb/core/render.py", line 625, in render_image
    data_bytes = a2b_base64(data.content)
binascii.Error: Invalid base64-encoded string: number of data characters (946073) cannot be 1 more than a multiple of 4
The full traceback has been saved in /tmp/sphinx-err-8jkumbwt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by hectormz** [comment]
Thanks @twiecki some binary blobs in GP-MaunaLoa2 got changed. Should be fixed now, and I checked all other notebooks for that change. 🤞

**Comment by hectormz** [comment]
🎉

**Comment by twiecki** [comment]
Thanks again @hectormz!

**Pull request merged**
